; Landmarks indexes (see data/maps/landmarks.asm)
	const_def

; Johto landmarks
	const LANDMARK_SPECIAL
	const LANDMARK_SILENT_HILLS
	const LANDMARK_JOHTO_ROUTE_1
	const LANDMARK_SAKURA_TOWN
	const LANDMARK_JOHTO_ROUTE_2
	const LANDMARK_JOHTO_ROUTE_3
	const LANDMARK_BELLFLOWER_CITY
	const LANDMARK_SPROUT_TOWER ; new name?
	const LANDMARK_HAUNTED_HOUSE
	const LANDMARK_RUINS_OF_ALPH
	const LANDMARK_JOHTO_ROUTE_4
	const LANDMARK_UNION_CAVE ; new name?
	const LANDMARK_JOHTO_ROUTE_5
	const LANDMARK_CYPRESS_TOWN
	const LANDMARK_JOHTO_ROUTE_6
	const LANDMARK_WHISPERING_WOODS ; Ilex Forest
	const LANDMARK_BEGONIA_TOWN
	const LANDMARK_JOHTO_ROUTE_7
	const LANDMARK_MARIGOLD_CITY
	const LANDMARK_JOHTO_RADIO_TOWER
	const LANDMARK_JOHTO_ROUTE_8
	const LANDMARK_JOHTO_POWER_PLANT
	const LANDMARK_JOHTO_ROUTE_9
	const LANDMARK_JOHTO_ROUTE_10
	const LANDMARK_MAPLE_CITY
	const LANDMARK_BRASS_TOWER
	const LANDMARK_TIN_TOWER
	const LANDMARK_JOHTO_ROUTE_11
	const LANDMARK_JOHTO_ROUTE_12
	const LANDMARK_AZURE_MIST_CITY
	const LANDMARK_LIGHTHOUSE
	const LANDMARK_SS_ANNE ; similar to Gen 1. train is how you get to Kanto.
	const LANDMARK_JOHTO_ROUTE_13 ; sea route
	const LANDMARK_WHIRL_ISLANDS ; new name?
	const LANDMARK_JOHTO_ROUTE_14 ; sea route
	const LANDMARK_JOHTO_ROUTE_15 ; sea route
	const LANDMARK_NATURE_PARK
	const LANDMARK_JOHTO_ROUTE_16
	const LANDMARK_ICE_PATH ; where mt mortar was, split between normal pines and snowy pines
	const LANDMARK_CEDAR_TOWN
	const LANDMARK_JOHTO_ROUTE_17
	const LANDMARK_WISTERIA_TOWN
	const LANDMARK_JOHTO_ROUTE_18
	const LANDMARK_EBONGROVE_CITY
	const LANDMARK_DRAGON_TEMPLE
	const LANDMARK_JOHTO_ROUTE_19
	const LANDMARK_DARK_CAVE ; new name?
	const LANDMARK_JOHTO_ROUTE_20
	const LANDMARK_JOHTO_ROUTE_21 ; badge check
	const LANDMARK_MT_FUJI ; victory road
	const LANDMARK_SILVER_CITY
	const LANDMARK_JOHTO_ROUTE_22
	const LANDMARK_TIDAL_CAVE ; where Tohjo Falls was. map changes based on time

KANTO_LANDMARK EQU const_value
	const LANDMARK_PALLET_TOWN
	const LANDMARK_KANTO_ROUTE_1
	const LANDMARK_VIRIDIAN_CITY
	const LANDMARK_KANTO_ROUTE_2
	const LANDMARK_VIRIDIAN_FOREST
	const LANDMARK_PEWTER_CITY
	const LANDMARK_KANTO_ROUTE_3
	const LANDMARK_MT_MOON
	const LANDMARK_KANTO_ROUTE_4
	const LANDMARK_CERULEAN_CITY
	const LANDMARK_KANTO_ROUTE_24
	const LANDMARK_KANTO_ROUTE_25
	const LANDMARK_KANTO_ROUTE_5
	const LANDMARK_UNDERGROUND_PATH
	const LANDMARK_KANTO_ROUTE_6
	const LANDMARK_VERMILION_CITY
	const LANDMARK_DIGLETTS_CAVE
	const LANDMARK_KANTO_ROUTE_9
	const LANDMARK_ROCK_TUNNEL
	const LANDMARK_KANTO_ROUTE_10
	const LANDMARK_KANTO_POWER_PLANT
	const LANDMARK_LAVENDER_TOWN
	const LANDMARK_POKEMON_TOWER
	const LANDMARK_KANTO_ROUTE_8
	const LANDMARK_KANTO_ROUTE_7
	const LANDMARK_CELADON_CITY
	const LANDMARK_SAFFRON_CITY
	const LANDMARK_SILPH_CO
	const LANDMARK_KANTO_RADIO_TOWER
	const LANDMARK_KANTO_ROUTE_11
	const LANDMARK_KANTO_ROUTE_12
	const LANDMARK_KANTO_ROUTE_13
	const LANDMARK_KANTO_ROUTE_14
	const LANDMARK_KANTO_ROUTE_15
	const LANDMARK_KANTO_ROUTE_16
	const LANDMARK_KANTO_ROUTE_17
	const LANDMARK_KANTO_ROUTE_18
	const LANDMARK_FUCHSIA_CITY
	const LANDMARK_SAFARI_ZONE
	const LANDMARK_KANTO_ROUTE_19
	const LANDMARK_KANTO_ROUTE_20
	const LANDMARK_SEAFOAM_ISLANDS
	const LANDMARK_CINNABAR_ISLAND
	const LANDMARK_POKEMON_MANSION
	const LANDMARK_KANTO_ROUTE_21
	const LANDMARK_KANTO_ROUTE_22
	const LANDMARK_KANTO_ROUTE_23
	const LANDMARK_VICTORY_ROAD
	const LANDMARK_INDIGO_PLATEAU
	const LANDMARK_CERULEAN_CAVE

; used in CaughtData
LANDMARK_GIFT  EQU $7e
LANDMARK_EVENT EQU $7f

; Regions
	const_def
	const JOHTO_REGION ; 0
	const KANTO_REGION ; 1
NUM_REGIONS EQU const_value
