; sprite ids
; OverworldSprites indexes (see data/sprites/sprites.asm)
	const_def
	const SPRITE_NONE ; 00
	const SPRITE_HIRO
	const SPRITE_HIRO_BIKE
	const SPRITE_SYLVIA
	const SPRITE_SYLVIA_BIKE
	const SPRITE_GAMEBOY_KID
	const SPRITE_SILVER
	const SPRITE_OAK
	const SPRITE_RED
	const SPRITE_BLUE
	const SPRITE_BILL
	const SPRITE_ELDER
	const SPRITE_JANINE
	const SPRITE_KURT
	const SPRITE_MOM
	const SPRITE_BLAINE
	const SPRITE_REDS_MOM
	const SPRITE_DAISY
	const SPRITE_ELM
	const SPRITE_WILL
	const SPRITE_FALKNER
	const SPRITE_WHITNEY
	const SPRITE_BUGSY
	const SPRITE_MORTY
	const SPRITE_CHUCK
	const SPRITE_JASMINE
	const SPRITE_PRYCE
	const SPRITE_CLAIR
	const SPRITE_BROCK
	const SPRITE_KAREN
	const SPRITE_BRUNO
	const SPRITE_MISTY
	const SPRITE_LANCE
	const SPRITE_SURGE
	const SPRITE_ERIKA
	const SPRITE_KOGA
	const SPRITE_SABRINA
	const SPRITE_COOLTRAINER_M
	const SPRITE_COOLTRAINER_F
	const SPRITE_BUG_CATCHER
	const SPRITE_TWIN
	const SPRITE_YOUNGSTER
	const SPRITE_LASS
	const SPRITE_TEACHER
	const SPRITE_BEAUTY
	const SPRITE_SUPER_NERD
	const SPRITE_ROCKER
	const SPRITE_POKEFAN_M
	const SPRITE_POKEFAN_F
	const SPRITE_GRAMPS
	const SPRITE_GRANNY
	const SPRITE_SWIMMER_GUY
	const SPRITE_SWIMMER_GIRL
	const SPRITE_BIG_SNORLAX
	const SPRITE_SURFING_PIKACHU
	const SPRITE_ROCKET
	const SPRITE_ROCKET_GIRL
	const SPRITE_NURSE
	const SPRITE_LINK_RECEPTIONIST
	const SPRITE_CLERK
	const SPRITE_FISHER
	const SPRITE_FISHING_GURU 
	const SPRITE_SCIENTIST
	const SPRITE_KIMONO_GIRL
	const SPRITE_SAGE
	const SPRITE_UNUSED_GUY
	const SPRITE_GENTLEMAN
	const SPRITE_BLACK_BELT
	const SPRITE_RECEPTIONIST
	const SPRITE_OFFICER
	const SPRITE_CAL
	const SPRITE_SLOWPOKE
	const SPRITE_CAPTAIN
	const SPRITE_BIG_LAPRAS
	const SPRITE_GYM_GUY
	const SPRITE_SAILOR
	const SPRITE_BIKER
	const SPRITE_PHARMACIST
	const SPRITE_MONSTER
	const SPRITE_FAIRY
	const SPRITE_BIRD 
	const SPRITE_DRAGON
	const SPRITE_BIG_ONIX
	const SPRITE_N64
	const SPRITE_SUDOWOODO
	const SPRITE_SURF
	const SPRITE_POKE_BALL
	const SPRITE_POKEDEX
	const SPRITE_PAPER
	const SPRITE_VIRTUAL_BOY
	const SPRITE_OLD_LINK_RECEPTIONIST
	const SPRITE_ROCK
	const SPRITE_BOULDER
	const SPRITE_SNES
	const SPRITE_FAMICOM
	const SPRITE_FRUIT_TREE
	const SPRITE_GOLD_TROPHY
	const SPRITE_SILVER_TROPHY

; SpriteMons indexes (see data/sprites/sprite_mons.asm)
	const_def $80
SPRITE_POKEMON EQU const_value
	const SPRITE_UNOWN ; 80
	const SPRITE_GEODUDE ; 81
	const SPRITE_GROWLITHE ; 82
	const SPRITE_WEEDLE ; 83
	const SPRITE_SHELLDER ; 84
	const SPRITE_ODDISH ; 85
	const SPRITE_GENGAR ; 86
	const SPRITE_ZUBAT ; 87
	const SPRITE_MAGIKARP ; 88
	const SPRITE_SQUIRTLE ; 89
	const SPRITE_TOGEPI ; 8a
	const SPRITE_BUTTERFREE ; 8b
	const SPRITE_DIGLETT ; 8c
	const SPRITE_POLIWAG ; 8d
	const SPRITE_PIKACHU ; 8e
	const SPRITE_CLEFAIRY ; 8f
	const SPRITE_CHARMANDER ; 90
	const SPRITE_JYNX ; 91
	const SPRITE_STARMIE ; 92
	const SPRITE_BULBASAUR ; 93
	const SPRITE_JIGGLYPUFF ; 94
	const SPRITE_GRIMER ; 95
	const SPRITE_EKANS ; 96
	const SPRITE_PARAS ; 97
	const SPRITE_TENTACOOL ; 98
	const SPRITE_TAUROS ; 99
	const SPRITE_MACHOP ; 9a
	const SPRITE_VOLTORB ; 9b
	const SPRITE_LAPRAS ; 9c
	const SPRITE_RHYDON ; 9d
	const SPRITE_MOLTRES ; 9e
	const SPRITE_SNORLAX ; 9f
	const SPRITE_GYARADOS ; a0
	const SPRITE_LUGIA ; a1
	const SPRITE_HO_OH ; a2

; special GetMonSprite values (see engine/overworld/overworld.asm)
	const_def $e0
	const SPRITE_DAY_CARE_MON_1 ; e0
	const SPRITE_DAY_CARE_MON_2 ; e1

; wVariableSprites indexes (see wram.asm)
	const_def $f0
SPRITE_VARS EQU const_value
	const SPRITE_CONSOLE ; f0
	const SPRITE_DOLL_1 ; f1
	const SPRITE_DOLL_2 ; f2
	const SPRITE_BIG_DOLL ; f3
	const SPRITE_WEIRD_TREE ; f4
	const SPRITE_OLIVINE_RIVAL ; f5
	const SPRITE_AZALEA_ROCKET ; f6
	const SPRITE_FUCHSIA_GYM_1 ; f7
	const SPRITE_FUCHSIA_GYM_2 ; f8
	const SPRITE_FUCHSIA_GYM_3 ; f9
	const SPRITE_FUCHSIA_GYM_4 ; fa
	const SPRITE_COPYCAT ; fb
	const SPRITE_JANINE_IMPERSONATOR ; fc
