INCLUDE "constants.asm"

SECTION "Pic Pointers", ROMX

INCLUDE "data/pokemon/pic_pointers.asm"


SECTION "Unown Pic Pointers", ROMX

INCLUDE "data/pokemon/unown_pic_pointers.asm"


SECTION "Trainer Pic Pointers", ROMX

INCLUDE "data/trainers/pic_pointers.asm"


SECTION "Pics 1", ROMX

BulbasaurFrontpic::   INCBIN "gfx/pokemon/gmon/bulbasaur.2bpp.lz"
BulbasaurBackpic::    INCBIN "gfx/pokemon/monback/bulbasaurb.2bpp.lz"
IvysaurFrontpic::     INCBIN "gfx/pokemon/gmon/ivysaur.2bpp.lz"
IvysaurBackpic::      INCBIN "gfx/pokemon/monback/ivysaurb.2bpp.lz"
VenusaurFrontpic::    INCBIN "gfx/pokemon/gmon/venusaur.2bpp.lz"
VenusaurBackpic::     INCBIN "gfx/pokemon/monback/venusaurb.2bpp.lz"
CharmanderFrontpic::  INCBIN "gfx/pokemon/gmon/charmander.2bpp.lz"
CharmanderBackpic::   INCBIN "gfx/pokemon/monback/charmanderb.2bpp.lz"
CharmeleonFrontpic::  INCBIN "gfx/pokemon/gmon/charmeleon.2bpp.lz"
CharmeleonBackpic::   INCBIN "gfx/pokemon/monback/charmeleonb.2bpp.lz"
CharizardFrontpic::   INCBIN "gfx/pokemon/gmon/charizard.2bpp.lz"
CharizardBackpic::    INCBIN "gfx/pokemon/monback/charizardb.2bpp.lz"
SquirtleFrontpic::    INCBIN "gfx/pokemon/gmon/squirtle.2bpp.lz"
SquirtleBackpic::     INCBIN "gfx/pokemon/monback/squirtleb.2bpp.lz"
WartortleFrontpic::   INCBIN "gfx/pokemon/gmon/wartortle.2bpp.lz"
WartortleBackpic::    INCBIN "gfx/pokemon/monback/wartortleb.2bpp.lz"
BlastoiseFrontpic::   INCBIN "gfx/pokemon/gmon/blastoise.2bpp.lz"
BlastoiseBackpic::    INCBIN "gfx/pokemon/monback/blastoiseb.2bpp.lz"
CaterpieFrontpic::    INCBIN "gfx/pokemon/gmon/caterpie.2bpp.lz"
CaterpieBackpic::     INCBIN "gfx/pokemon/monback/caterpieb.2bpp.lz"
MetapodFrontpic::     INCBIN "gfx/pokemon/gmon/metapod.2bpp.lz"
MetapodBackpic::      INCBIN "gfx/pokemon/monback/metapodb.2bpp.lz"
ButterfreeFrontpic::  INCBIN "gfx/pokemon/gmon/butterfree.2bpp.lz"
ButterfreeBackpic::   INCBIN "gfx/pokemon/monback/butterfreeb.2bpp.lz"
WeedleFrontpic::      INCBIN "gfx/pokemon/gmon/weedle.2bpp.lz"
WeedleBackpic::       INCBIN "gfx/pokemon/monback/weedleb.2bpp.lz"
KakunaFrontpic::      INCBIN "gfx/pokemon/gmon/kakuna.2bpp.lz"
KakunaBackpic::       INCBIN "gfx/pokemon/monback/kakunab.2bpp.lz"
BeedrillFrontpic::    INCBIN "gfx/pokemon/gmon/beedrill.2bpp.lz"
BeedrillBackpic::     INCBIN "gfx/pokemon/monback/beedrillb.2bpp.lz"
PidgeyFrontpic::      INCBIN "gfx/pokemon/gmon/pidgey.2bpp.lz"
PidgeyBackpic::       INCBIN "gfx/pokemon/monback/pidgeyb.2bpp.lz"
PidgeottoFrontpic::   INCBIN "gfx/pokemon/gmon/pidgeotto.2bpp.lz"
PidgeottoBackpic::    INCBIN "gfx/pokemon/monback/pidgeottob.2bpp.lz"
PidgeotFrontpic::     INCBIN "gfx/pokemon/gmon/pidgeot.2bpp.lz"
PidgeotBackpic::      INCBIN "gfx/pokemon/monback/pidgeotb.2bpp.lz"
RattataFrontpic::     INCBIN "gfx/pokemon/gmon/rattata.2bpp.lz"
RattataBackpic::      INCBIN "gfx/pokemon/monback/rattatab.2bpp.lz"
RaticateFrontpic::    INCBIN "gfx/pokemon/gmon/raticate.2bpp.lz"
RaticateBackpic::     INCBIN "gfx/pokemon/monback/raticateb.2bpp.lz"
SpearowFrontpic::     INCBIN "gfx/pokemon/gmon/spearow.2bpp.lz"
SpearowBackpic::      INCBIN "gfx/pokemon/monback/spearowb.2bpp.lz"
FearowFrontpic::      INCBIN "gfx/pokemon/gmon/fearow.2bpp.lz"
FearowBackpic::       INCBIN "gfx/pokemon/monback/fearowb.2bpp.lz"
EkansFrontpic::       INCBIN "gfx/pokemon/gmon/ekans.2bpp.lz"
EkansBackpic::        INCBIN "gfx/pokemon/monback/ekansb.2bpp.lz"


SECTION "Pics 2", ROMX

ArbokFrontpic::       INCBIN "gfx/pokemon/gmon/arbok.2bpp.lz"
ArbokBackpic::        INCBIN "gfx/pokemon/monback/arbokb.2bpp.lz"
PikachuFrontpic::     INCBIN "gfx/pokemon/gmon/pikachu.2bpp.lz"
PikachuBackpic::      INCBIN "gfx/pokemon/monback/pikachub.2bpp.lz"
RaichuFrontpic::      INCBIN "gfx/pokemon/gmon/raichu.2bpp.lz"
RaichuBackpic::       INCBIN "gfx/pokemon/monback/raichub.2bpp.lz"
SandshrewFrontpic::   INCBIN "gfx/pokemon/gmon/sandshrew.2bpp.lz"
SandshrewBackpic::    INCBIN "gfx/pokemon/monback/sandshrewb.2bpp.lz"
SandslashFrontpic::   INCBIN "gfx/pokemon/gmon/sandslash.2bpp.lz"
SandslashBackpic::    INCBIN "gfx/pokemon/monback/sandslashb.2bpp.lz"
NidoranFFrontpic::    INCBIN "gfx/pokemon/gmon/nidoranf.2bpp.lz"
NidoranFBackpic::     INCBIN "gfx/pokemon/monback/nidoranfb.2bpp.lz"
NidorinaFrontpic::    INCBIN "gfx/pokemon/gmon/nidorina.2bpp.lz"
NidorinaBackpic::     INCBIN "gfx/pokemon/monback/nidorinab.2bpp.lz"
NidoqueenFrontpic::   INCBIN "gfx/pokemon/gmon/nidoqueen.2bpp.lz"
NidoqueenBackpic::    INCBIN "gfx/pokemon/monback/nidoqueenb.2bpp.lz"
NidoranMFrontpic::    INCBIN "gfx/pokemon/gmon/nidoranm.2bpp.lz"
NidoranMBackpic::     INCBIN "gfx/pokemon/monback/nidoranmb.2bpp.lz"
NidorinoFrontpic::    INCBIN "gfx/pokemon/gmon/nidorino.2bpp.lz"
NidorinoBackpic::     INCBIN "gfx/pokemon/monback/nidorinob.2bpp.lz"
NidokingFrontpic::    INCBIN "gfx/pokemon/gmon/nidoking.2bpp.lz"
NidokingBackpic::     INCBIN "gfx/pokemon/monback/nidokingb.2bpp.lz"
ClefairyFrontpic::    INCBIN "gfx/pokemon/gmon/clefairy.2bpp.lz"
ClefairyBackpic::     INCBIN "gfx/pokemon/monback/clefairyb.2bpp.lz"
ClefableFrontpic::    INCBIN "gfx/pokemon/gmon/clefable.2bpp.lz"
ClefableBackpic::     INCBIN "gfx/pokemon/monback/clefableb.2bpp.lz"
VulpixFrontpic::      INCBIN "gfx/pokemon/gmon/vulpix.2bpp.lz"
VulpixBackpic::       INCBIN "gfx/pokemon/monback/vulpixb.2bpp.lz"
NinetalesFrontpic::   INCBIN "gfx/pokemon/gmon/ninetales.2bpp.lz"
NinetalesBackpic::    INCBIN "gfx/pokemon/monback/ninetalesb.2bpp.lz"
JigglypuffFrontpic::  INCBIN "gfx/pokemon/gmon/jigglypuff.2bpp.lz"
JigglypuffBackpic::   INCBIN "gfx/pokemon/monback/jigglypuffb.2bpp.lz"
WigglytuffFrontpic::  INCBIN "gfx/pokemon/gmon/wigglytuff.2bpp.lz"
WigglytuffBackpic::   INCBIN "gfx/pokemon/monback/wigglytuffb.2bpp.lz"
ZubatFrontpic::       INCBIN "gfx/pokemon/gmon/zubat.2bpp.lz"
ZubatBackpic::        INCBIN "gfx/pokemon/monback/zubatb.2bpp.lz"
GolbatFrontpic::      INCBIN "gfx/pokemon/gmon/golbat.2bpp.lz"
GolbatBackpic::       INCBIN "gfx/pokemon/monback/golbatb.2bpp.lz"
OddishFrontpic::      INCBIN "gfx/pokemon/gmon/oddish.2bpp.lz"
OddishBackpic::       INCBIN "gfx/pokemon/monback/oddishb.2bpp.lz"
GloomFrontpic::       INCBIN "gfx/pokemon/gmon/gloom.2bpp.lz"
GloomBackpic::        INCBIN "gfx/pokemon/monback/gloomb.2bpp.lz"


SECTION "Pics 3", ROMX

VileplumeFrontpic::   INCBIN "gfx/pokemon/gmon/vileplume.2bpp.lz"
VileplumeBackpic::    INCBIN "gfx/pokemon/monback/vileplumeb.2bpp.lz"
ParasFrontpic::       INCBIN "gfx/pokemon/gmon/paras.2bpp.lz"
ParasBackpic::        INCBIN "gfx/pokemon/monback/parasb.2bpp.lz"
ParasectFrontpic::    INCBIN "gfx/pokemon/gmon/parasect.2bpp.lz"
ParasectBackpic::     INCBIN "gfx/pokemon/monback/parasectb.2bpp.lz"
VenonatFrontpic::     INCBIN "gfx/pokemon/gmon/venonat.2bpp.lz"
VenonatBackpic::      INCBIN "gfx/pokemon/monback/venonatb.2bpp.lz"
VenomothFrontpic::    INCBIN "gfx/pokemon/gmon/venomoth.2bpp.lz"
VenomothBackpic::     INCBIN "gfx/pokemon/monback/venomothb.2bpp.lz"
DiglettFrontpic::     INCBIN "gfx/pokemon/gmon/diglett.2bpp.lz"
DiglettBackpic::      INCBIN "gfx/pokemon/monback/diglettb.2bpp.lz"
DugtrioFrontpic::     INCBIN "gfx/pokemon/gmon/dugtrio.2bpp.lz"
DugtrioBackpic::      INCBIN "gfx/pokemon/monback/dugtriob.2bpp.lz"
MeowthFrontpic::      INCBIN "gfx/pokemon/gmon/meowth.2bpp.lz"
MeowthBackpic::       INCBIN "gfx/pokemon/monback/meowthb.2bpp.lz"
PersianFrontpic::     INCBIN "gfx/pokemon/gmon/persian.2bpp.lz"
PersianBackpic::      INCBIN "gfx/pokemon/monback/persianb.2bpp.lz"
PsyduckFrontpic::     INCBIN "gfx/pokemon/gmon/psyduck.2bpp.lz"
PsyduckBackpic::      INCBIN "gfx/pokemon/monback/psyduckb.2bpp.lz"
GolduckFrontpic::     INCBIN "gfx/pokemon/gmon/golduck.2bpp.lz"
GolduckBackpic::      INCBIN "gfx/pokemon/monback/golduckb.2bpp.lz"
MankeyFrontpic::      INCBIN "gfx/pokemon/gmon/mankey.2bpp.lz"
MankeyBackpic::       INCBIN "gfx/pokemon/monback/mankeyb.2bpp.lz"
PrimeapeFrontpic::    INCBIN "gfx/pokemon/gmon/primeape.2bpp.lz"
PrimeapeBackpic::     INCBIN "gfx/pokemon/monback/primeapeb.2bpp.lz"
GrowlitheFrontpic::   INCBIN "gfx/pokemon/gmon/growlithe.2bpp.lz"
GrowlitheBackpic::    INCBIN "gfx/pokemon/monback/growlitheb.2bpp.lz"
ArcanineFrontpic::    INCBIN "gfx/pokemon/gmon/arcanine.2bpp.lz"
ArcanineBackpic::     INCBIN "gfx/pokemon/monback/arcanineb.2bpp.lz"
PoliwagFrontpic::     INCBIN "gfx/pokemon/gmon/poliwag.2bpp.lz"
PoliwagBackpic::      INCBIN "gfx/pokemon/monback/poliwagb.2bpp.lz"
PoliwhirlFrontpic::   INCBIN "gfx/pokemon/gmon/poliwhirl.2bpp.lz"
PoliwhirlBackpic::    INCBIN "gfx/pokemon/monback/poliwhirlb.2bpp.lz"
PoliwrathFrontpic::   INCBIN "gfx/pokemon/gmon/poliwrath.2bpp.lz"
PoliwrathBackpic::    INCBIN "gfx/pokemon/monback/poliwrathb.2bpp.lz"
AbraFrontpic::        INCBIN "gfx/pokemon/gmon/abra.2bpp.lz"
AbraBackpic::         INCBIN "gfx/pokemon/monback/abrab.2bpp.lz"
KadabraFrontpic::     INCBIN "gfx/pokemon/gmon/kadabra.2bpp.lz"
KadabraBackpic::      INCBIN "gfx/pokemon/monback/kadabrab.2bpp.lz"
AlakazamFrontpic::    INCBIN "gfx/pokemon/gmon/alakazam.2bpp.lz"
AlakazamBackpic::     INCBIN "gfx/pokemon/monback/alakazamb.2bpp.lz"


SECTION "Pics 4", ROMX

MachopFrontpic::      INCBIN "gfx/pokemon/gmon/machop.2bpp.lz"
MachopBackpic::       INCBIN "gfx/pokemon/monback/machopb.2bpp.lz"
MachokeFrontpic::     INCBIN "gfx/pokemon/gmon/machoke.2bpp.lz"
MachokeBackpic::      INCBIN "gfx/pokemon/monback/machokeb.2bpp.lz"
MachampFrontpic::     INCBIN "gfx/pokemon/gmon/machamp.2bpp.lz"
MachampBackpic::      INCBIN "gfx/pokemon/monback/machampb.2bpp.lz"
BellsproutFrontpic::  INCBIN "gfx/pokemon/gmon/bellsprout.2bpp.lz"
BellsproutBackpic::   INCBIN "gfx/pokemon/monback/bellsproutb.2bpp.lz"
WeepinbellFrontpic::  INCBIN "gfx/pokemon/gmon/weepinbell.2bpp.lz"
WeepinbellBackpic::   INCBIN "gfx/pokemon/monback/weepinbellb.2bpp.lz"
VictreebelFrontpic::  INCBIN "gfx/pokemon/gmon/victreebel.2bpp.lz"
VictreebelBackpic::   INCBIN "gfx/pokemon/monback/victreebelb.2bpp.lz"
TentacoolFrontpic::   INCBIN "gfx/pokemon/gmon/tentacool.2bpp.lz"
TentacoolBackpic::    INCBIN "gfx/pokemon/monback/tentacoolb.2bpp.lz"
TentacruelFrontpic::  INCBIN "gfx/pokemon/gmon/tentacruel.2bpp.lz"
TentacruelBackpic::   INCBIN "gfx/pokemon/monback/tentacruelb.2bpp.lz"
GeodudeFrontpic::     INCBIN "gfx/pokemon/gmon/geodude.2bpp.lz"
GeodudeBackpic::      INCBIN "gfx/pokemon/monback/geodudeb.2bpp.lz"
GravelerFrontpic::    INCBIN "gfx/pokemon/gmon/graveler.2bpp.lz"
GravelerBackpic::     INCBIN "gfx/pokemon/monback/gravelerb.2bpp.lz"
GolemFrontpic::       INCBIN "gfx/pokemon/gmon/golem.2bpp.lz"
GolemBackpic::        INCBIN "gfx/pokemon/monback/golemb.2bpp.lz"
PonytaFrontpic::      INCBIN "gfx/pokemon/gmon/ponyta.2bpp.lz"
PonytaBackpic::       INCBIN "gfx/pokemon/monback/ponytab.2bpp.lz"
RapidashFrontpic::    INCBIN "gfx/pokemon/gmon/rapidash.2bpp.lz"
RapidashBackpic::     INCBIN "gfx/pokemon/monback/rapidashb.2bpp.lz"
SlowpokeFrontpic::    INCBIN "gfx/pokemon/gmon/slowpoke.2bpp.lz"
SlowpokeBackpic::     INCBIN "gfx/pokemon/monback/slowpokeb.2bpp.lz"
SlowbroFrontpic::     INCBIN "gfx/pokemon/gmon/slowbro.2bpp.lz"
SlowbroBackpic::      INCBIN "gfx/pokemon/monback/slowbrob.2bpp.lz"
MagnemiteFrontpic::   INCBIN "gfx/pokemon/gmon/magnemite.2bpp.lz"
MagnemiteBackpic::    INCBIN "gfx/pokemon/monback/magnemiteb.2bpp.lz"
MagnetonFrontpic::    INCBIN "gfx/pokemon/gmon/magneton.2bpp.lz"
MagnetonBackpic::     INCBIN "gfx/pokemon/monback/magnetonb.2bpp.lz"
FarfetchDFrontpic::   INCBIN "gfx/pokemon/gmon/farfetchd.2bpp.lz"
FarfetchDBackpic::    INCBIN "gfx/pokemon/monback/farfetchdb.2bpp.lz"
DoduoFrontpic::       INCBIN "gfx/pokemon/gmon/doduo.2bpp.lz"
DoduoBackpic::        INCBIN "gfx/pokemon/monback/doduob.2bpp.lz"
DodrioFrontpic::      INCBIN "gfx/pokemon/gmon/dodrio.2bpp.lz"
DodrioBackpic::       INCBIN "gfx/pokemon/monback/dodriob.2bpp.lz"
SeelFrontpic::        INCBIN "gfx/pokemon/gmon/seel.2bpp.lz"
SeelBackpic::         INCBIN "gfx/pokemon/monback/seelb.2bpp.lz"


SECTION "Pics 5", ROMX

DewgongFrontpic::     INCBIN "gfx/pokemon/gmon/dewgong.2bpp.lz"
DewgongBackpic::      INCBIN "gfx/pokemon/monback/dewgongb.2bpp.lz"
GrimerFrontpic::      INCBIN "gfx/pokemon/gmon/grimer.2bpp.lz"
GrimerBackpic::       INCBIN "gfx/pokemon/monback/grimerb.2bpp.lz"
MukFrontpic::         INCBIN "gfx/pokemon/gmon/muk.2bpp.lz"
MukBackpic::          INCBIN "gfx/pokemon/monback/mukb.2bpp.lz"
ShellderFrontpic::    INCBIN "gfx/pokemon/gmon/shellder.2bpp.lz"
ShellderBackpic::     INCBIN "gfx/pokemon/monback/shellderb.2bpp.lz"
CloysterFrontpic::    INCBIN "gfx/pokemon/gmon/cloyster.2bpp.lz"
CloysterBackpic::     INCBIN "gfx/pokemon/monback/cloysterb.2bpp.lz"
GastlyFrontpic::      INCBIN "gfx/pokemon/gmon/gastly.2bpp.lz"
GastlyBackpic::       INCBIN "gfx/pokemon/monback/gastlyb.2bpp.lz"
HaunterFrontpic::     INCBIN "gfx/pokemon/gmon/haunter.2bpp.lz"
HaunterBackpic::      INCBIN "gfx/pokemon/monback/haunterb.2bpp.lz"
GengarFrontpic::      INCBIN "gfx/pokemon/gmon/gengar.2bpp.lz"
GengarBackpic::       INCBIN "gfx/pokemon/monback/gengarb.2bpp.lz"
OnixFrontpic::        INCBIN "gfx/pokemon/gmon/onix.2bpp.lz"
OnixBackpic::         INCBIN "gfx/pokemon/monback/onixb.2bpp.lz"
DrowzeeFrontpic::     INCBIN "gfx/pokemon/gmon/drowzee.2bpp.lz"
DrowzeeBackpic::      INCBIN "gfx/pokemon/monback/drowzeeb.2bpp.lz"
HypnoFrontpic::       INCBIN "gfx/pokemon/gmon/hypno.2bpp.lz"
HypnoBackpic::        INCBIN "gfx/pokemon/monback/hypnob.2bpp.lz"
KrabbyFrontpic::       INCBIN "gfx/pokemon/gmon/krabby.2bpp.lz"
KrabbyBackpic::        INCBIN "gfx/pokemon/monback/krabbyb.2bpp.lz"
KinglerFrontpic::      INCBIN "gfx/pokemon/gmon/kingler.2bpp.lz"
KinglerBackpic::       INCBIN "gfx/pokemon/monback/kinglerb.2bpp.lz"
VoltorbFrontpic::      INCBIN "gfx/pokemon/gmon/voltorb.2bpp.lz"
VoltorbBackpic::       INCBIN "gfx/pokemon/monback/voltorbb.2bpp.lz"
ElectrodeFrontpic::    INCBIN "gfx/pokemon/gmon/electrode.2bpp.lz"
ElectrodeBackpic::     INCBIN "gfx/pokemon/monback/electrodeb.2bpp.lz"
ExeggcuteFrontpic::    INCBIN "gfx/pokemon/gmon/exeggcute.2bpp.lz"
ExeggcuteBackpic::     INCBIN "gfx/pokemon/monback/exeggcuteb.2bpp.lz"
ExeggutorFrontpic::    INCBIN "gfx/pokemon/gmon/exeggutor.2bpp.lz"
ExeggutorBackpic::     INCBIN "gfx/pokemon/monback/exeggutorb.2bpp.lz"
CuboneFrontpic::       INCBIN "gfx/pokemon/gmon/cubone.2bpp.lz"
CuboneBackpic::        INCBIN "gfx/pokemon/monback/cuboneb.2bpp.lz"
MarowakFrontpic::      INCBIN "gfx/pokemon/gmon/marowak.2bpp.lz"
MarowakBackpic::       INCBIN "gfx/pokemon/monback/marowakb.2bpp.lz"
HitmonleeFrontpic::    INCBIN "gfx/pokemon/gmon/hitmonlee.2bpp.lz"
HitmonleeBackpic::     INCBIN "gfx/pokemon/monback/hitmonleeb.2bpp.lz"
HitmonchanFrontpic::   INCBIN "gfx/pokemon/gmon/hitmonchan.2bpp.lz"
HitmonchanBackpic::    INCBIN "gfx/pokemon/monback/hitmonchanb.2bpp.lz"


SECTION "Pics 6", ROMX

LickitungFrontpic::    INCBIN "gfx/pokemon/gmon/lickitung.2bpp.lz"
LickitungBackpic::     INCBIN "gfx/pokemon/monback/lickitungb.2bpp.lz"
KoffingFrontpic::      INCBIN "gfx/pokemon/gmon/koffing.2bpp.lz"
KoffingBackpic::       INCBIN "gfx/pokemon/monback/koffingb.2bpp.lz"
WeezingFrontpic::      INCBIN "gfx/pokemon/gmon/weezing.2bpp.lz"
WeezingBackpic::       INCBIN "gfx/pokemon/monback/weezingb.2bpp.lz"
RhyhornFrontpic::      INCBIN "gfx/pokemon/gmon/rhyhorn.2bpp.lz"
RhyhornBackpic::       INCBIN "gfx/pokemon/monback/rhyhornb.2bpp.lz"
RhydonFrontpic::       INCBIN "gfx/pokemon/gmon/rhydon.2bpp.lz"
RhydonBackpic::        INCBIN "gfx/pokemon/monback/rhydonb.2bpp.lz"
ChanseyFrontpic::      INCBIN "gfx/pokemon/gmon/chansey.2bpp.lz"
ChanseyBackpic::       INCBIN "gfx/pokemon/monback/chanseyb.2bpp.lz"
TangelaFrontpic::      INCBIN "gfx/pokemon/gmon/tangela.2bpp.lz"
TangelaBackpic::       INCBIN "gfx/pokemon/monback/tangelab.2bpp.lz"
KangaskhanFrontpic::   INCBIN "gfx/pokemon/gmon/kangaskhan.2bpp.lz"
KangaskhanBackpic::    INCBIN "gfx/pokemon/monback/kangaskhanb.2bpp.lz"
HorseaFrontpic::      INCBIN "gfx/pokemon/gmon/horsea.2bpp.lz"
HorseaBackpic::       INCBIN "gfx/pokemon/monback/horseab.2bpp.lz"
SeadraFrontpic::      INCBIN "gfx/pokemon/gmon/seadra.2bpp.lz"
SeadraBackpic::       INCBIN "gfx/pokemon/monback/seadrab.2bpp.lz"
GoldeenFrontpic::     INCBIN "gfx/pokemon/gmon/goldeen.2bpp.lz"
GoldeenBackpic::      INCBIN "gfx/pokemon/monback/goldeenb.2bpp.lz"
SeakingFrontpic::     INCBIN "gfx/pokemon/gmon/seaking.2bpp.lz"
SeakingBackpic::      INCBIN "gfx/pokemon/monback/seakingb.2bpp.lz"
StaryuFrontpic::      INCBIN "gfx/pokemon/gmon/staryu.2bpp.lz"
StaryuBackpic::       INCBIN "gfx/pokemon/monback/staryub.2bpp.lz"
StarmieFrontpic::     INCBIN "gfx/pokemon/gmon/starmie.2bpp.lz"
StarmieBackpic::      INCBIN "gfx/pokemon/monback/starmieb.2bpp.lz"
MrMimeFrontpic::      INCBIN "gfx/pokemon/gmon/mr.mime.2bpp.lz"
MrMimeBackpic::       INCBIN "gfx/pokemon/monback/mr.mimeb.2bpp.lz"
ScytherFrontpic::     INCBIN "gfx/pokemon/gmon/scyther.2bpp.lz"
ScytherBackpic::      INCBIN "gfx/pokemon/monback/scytherb.2bpp.lz"
JynxFrontpic::        INCBIN "gfx/pokemon/gmon/jynx.2bpp.lz"
JynxBackpic::         INCBIN "gfx/pokemon/monback/jynxb.2bpp.lz"
ElectabuzzFrontpic::  INCBIN "gfx/pokemon/gmon/electabuzz.2bpp.lz"
ElectabuzzBackpic::   INCBIN "gfx/pokemon/monback/electabuzzb.2bpp.lz"
MagmarFrontpic::      INCBIN "gfx/pokemon/gmon/magmar.2bpp.lz"
MagmarBackpic::       INCBIN "gfx/pokemon/monback/magmarb.2bpp.lz"
PinsirFrontpic::      INCBIN "gfx/pokemon/gmon/pinsir.2bpp.lz"
PinsirBackpic::       INCBIN "gfx/pokemon/monback/pinsirb.2bpp.lz"


SECTION "Pics 7", ROMX

TaurosFrontpic::      INCBIN "gfx/pokemon/gmon/tauros.2bpp.lz"
TaurosBackpic::       INCBIN "gfx/pokemon/monback/taurosb.2bpp.lz"
MagikarpFrontpic::    INCBIN "gfx/pokemon/gmon/magikarp.2bpp.lz"
MagikarpBackpic::     INCBIN "gfx/pokemon/monback/magikarpb.2bpp.lz"
GyaradosFrontpic::    INCBIN "gfx/pokemon/gmon/gyarados.2bpp.lz"
GyaradosBackpic::     INCBIN "gfx/pokemon/monback/gyaradosb.2bpp.lz"
LaprasFrontpic::      INCBIN "gfx/pokemon/gmon/lapras.2bpp.lz"
LaprasBackpic::       INCBIN "gfx/pokemon/monback/laprasb.2bpp.lz"
DittoFrontpic::       INCBIN "gfx/pokemon/gmon/ditto.2bpp.lz"
DittoBackpic::        INCBIN "gfx/pokemon/monback/dittob.2bpp.lz"
EeveeFrontpic::       INCBIN "gfx/pokemon/gmon/eevee.2bpp.lz"
EeveeBackpic::        INCBIN "gfx/pokemon/monback/eeveeb.2bpp.lz"
VaporeonFrontpic::    INCBIN "gfx/pokemon/gmon/vaporeon.2bpp.lz"
VaporeonBackpic::     INCBIN "gfx/pokemon/monback/vaporeonb.2bpp.lz"
JolteonFrontpic::     INCBIN "gfx/pokemon/gmon/jolteon.2bpp.lz"
JolteonBackpic::      INCBIN "gfx/pokemon/monback/jolteonb.2bpp.lz"
FlareonFrontpic::     INCBIN "gfx/pokemon/gmon/flareon.2bpp.lz"
FlareonBackpic::      INCBIN "gfx/pokemon/monback/flareonb.2bpp.lz"
PorygonFrontpic::     INCBIN "gfx/pokemon/gmon/porygon.2bpp.lz"
PorygonBackpic::      INCBIN "gfx/pokemon/monback/porygonb.2bpp.lz"
OmanyteFrontpic::     INCBIN "gfx/pokemon/gmon/omanyte.2bpp.lz"
OmanyteBackpic::      INCBIN "gfx/pokemon/monback/omanyteb.2bpp.lz"
OmastarFrontpic::     INCBIN "gfx/pokemon/gmon/omastar.2bpp.lz"
OmastarBackpic::      INCBIN "gfx/pokemon/monback/omastarb.2bpp.lz"
KabutoFrontpic::      INCBIN "gfx/pokemon/gmon/kabuto.2bpp.lz"
KabutoBackpic::       INCBIN "gfx/pokemon/monback/kabutob.2bpp.lz"
KabutopsFrontpic::    INCBIN "gfx/pokemon/gmon/kabutops.2bpp.lz"
KabutopsBackpic::     INCBIN "gfx/pokemon/monback/kabutopsb.2bpp.lz"
AerodactylFrontpic::  INCBIN "gfx/pokemon/gmon/aerodactyl.2bpp.lz"
AerodactylBackpic::   INCBIN "gfx/pokemon/monback/aerodactylb.2bpp.lz"
SnorlaxFrontpic::     INCBIN "gfx/pokemon/gmon/snorlax.2bpp.lz"
SnorlaxBackpic::      INCBIN "gfx/pokemon/monback/snorlaxb.2bpp.lz"
ArticunoFrontpic::    INCBIN "gfx/pokemon/gmon/articuno.2bpp.lz"
ArticunoBackpic::     INCBIN "gfx/pokemon/monback/articunob.2bpp.lz"
ZapdosFrontpic::      INCBIN "gfx/pokemon/gmon/zapdos.2bpp.lz"
ZapdosBackpic::       INCBIN "gfx/pokemon/monback/zapdosb.2bpp.lz"
MoltresFrontpic::     INCBIN "gfx/pokemon/gmon/moltres.2bpp.lz"
MoltresBackpic::      INCBIN "gfx/pokemon/monback/moltresb.2bpp.lz"
DratiniFrontpic::     INCBIN "gfx/pokemon/gmon/dratini.2bpp.lz"
DratiniBackpic::      INCBIN "gfx/pokemon/monback/dratinib.2bpp.lz"
DragonairFrontpic::   INCBIN "gfx/pokemon/gmon/dragonair.2bpp.lz"
DragonairBackpic::    INCBIN "gfx/pokemon/monback/dragonairb.2bpp.lz"


SECTION "Pics 8", ROMX

DragoniteFrontpic::   INCBIN "gfx/pokemon/gmon/dragonite.2bpp.lz"
DragoniteBackpic::    INCBIN "gfx/pokemon/monback/dragoniteb.2bpp.lz"
MewtwoFrontpic::      INCBIN "gfx/pokemon/gmon/mewtwo.2bpp.lz"
MewtwoBackpic::       INCBIN "gfx/pokemon/monback/mewtwob.2bpp.lz"
MewFrontpic::         INCBIN "gfx/pokemon/gmon/mew.2bpp.lz"
MewBackpic::          INCBIN "gfx/pokemon/monback/mewb.2bpp.lz"
ChikoritaFrontpic::   INCBIN "gfx/pokemon/gmon/chikorita.2bpp.lz"
ChikoritaBackpic::    INCBIN "gfx/pokemon/monback/chikoritab.2bpp.lz"
BayleefFrontpic::     INCBIN "gfx/pokemon/gmon/bayleef.2bpp.lz"
BayleefBackpic::      INCBIN "gfx/pokemon/monback/bayleefb.2bpp.lz"
MeganiumFrontpic::    INCBIN "gfx/pokemon/gmon/meganium.2bpp.lz"
MeganiumBackpic::     INCBIN "gfx/pokemon/monback/meganiumb.2bpp.lz"
CyndaquilFrontpic::   INCBIN "gfx/pokemon/gmon/cyndaquil.2bpp.lz"
CyndaquilBackpic::    INCBIN "gfx/pokemon/monback/cyndaquilb.2bpp.lz"
QuilavaFrontpic::     INCBIN "gfx/pokemon/gmon/quilava.2bpp.lz"
QuilavaBackpic::      INCBIN "gfx/pokemon/monback/quilavab.2bpp.lz"
TyphlosionFrontpic::  INCBIN "gfx/pokemon/gmon/typhlosion.2bpp.lz"
TyphlosionBackpic::   INCBIN "gfx/pokemon/monback/typhlosionb.2bpp.lz"
TotodileFrontpic::    INCBIN "gfx/pokemon/gmon/totodile.2bpp.lz"
TotodileBackpic::     INCBIN "gfx/pokemon/monback/totodileb.2bpp.lz"
CroconawFrontpic::    INCBIN "gfx/pokemon/gmon/croconaw.2bpp.lz"
CroconawBackpic::     INCBIN "gfx/pokemon/monback/croconawb.2bpp.lz"
FeraligatrFrontpic::  INCBIN "gfx/pokemon/gmon/feraligatr.2bpp.lz"
FeraligatrBackpic::   INCBIN "gfx/pokemon/monback/feraligatrb.2bpp.lz"
SentretFrontpic::     INCBIN "gfx/pokemon/gmon/sentret.2bpp.lz"
SentretBackpic::      INCBIN "gfx/pokemon/monback/sentretb.2bpp.lz"
FurretFrontpic::      INCBIN "gfx/pokemon/gmon/furret.2bpp.lz"
FurretBackpic::       INCBIN "gfx/pokemon/monback/furretb.2bpp.lz"
HoothootFrontpic::    INCBIN "gfx/pokemon/gmon/hoothoot.2bpp.lz"
HoothootBackpic::     INCBIN "gfx/pokemon/monback/hoothootb.2bpp.lz"
NoctowlFrontpic::     INCBIN "gfx/pokemon/gmon/noctowl.2bpp.lz"
NoctowlBackpic::      INCBIN "gfx/pokemon/monback/noctowlb.2bpp.lz"
LedybaFrontpic::      INCBIN "gfx/pokemon/gmon/ledyba.2bpp.lz"
LedybaBackpic::       INCBIN "gfx/pokemon/monback/ledybab.2bpp.lz"
LedianFrontpic::      INCBIN "gfx/pokemon/gmon/ledian.2bpp.lz"
LedianBackpic::       INCBIN "gfx/pokemon/monback/ledianb.2bpp.lz"
SpinarakFrontpic::    INCBIN "gfx/pokemon/gmon/spinarak.2bpp.lz"
SpinarakBackpic::     INCBIN "gfx/pokemon/monback/spinarakb.2bpp.lz"
AriadosFrontpic::     INCBIN "gfx/pokemon/gmon/ariados.2bpp.lz"
AriadosBackpic::      INCBIN "gfx/pokemon/monback/ariadosb.2bpp.lz"
CrobatFrontpic::      INCBIN "gfx/pokemon/gmon/crobat.2bpp.lz"
CrobatBackpic::       INCBIN "gfx/pokemon/monback/crobatb.2bpp.lz"


SECTION "Pics 9", ROMX

ChinchouFrontpic::    INCBIN "gfx/pokemon/gmon/chinchou.2bpp.lz"
ChinchouBackpic::     INCBIN "gfx/pokemon/monback/chinchoub.2bpp.lz"
LanturnFrontpic::     INCBIN "gfx/pokemon/gmon/lanturn.2bpp.lz"
LanturnBackpic::      INCBIN "gfx/pokemon/monback/lanturnb.2bpp.lz"
PichuFrontpic::       INCBIN "gfx/pokemon/gmon/pichu.2bpp.lz"
PichuBackpic::        INCBIN "gfx/pokemon/monback/pichub.2bpp.lz"
CleffaFrontpic::      INCBIN "gfx/pokemon/gmon/cleffa.2bpp.lz"
CleffaBackpic::       INCBIN "gfx/pokemon/monback/cleffab.2bpp.lz"
IgglybuffFrontpic::   INCBIN "gfx/pokemon/gmon/igglybuff.2bpp.lz"
IgglybuffBackpic::    INCBIN "gfx/pokemon/monback/igglybuffb.2bpp.lz"
TogepiFrontpic::      INCBIN "gfx/pokemon/gmon/togepi.2bpp.lz"
TogepiBackpic::       INCBIN "gfx/pokemon/monback/togepib.2bpp.lz"
TogeticFrontpic::     INCBIN "gfx/pokemon/gmon/togetic.2bpp.lz"
TogeticBackpic::      INCBIN "gfx/pokemon/monback/togeticb.2bpp.lz"
NatuFrontpic::        INCBIN "gfx/pokemon/gmon/natu.2bpp.lz"
NatuBackpic::         INCBIN "gfx/pokemon/monback/natub.2bpp.lz"
XatuFrontpic::        INCBIN "gfx/pokemon/gmon/xatu.2bpp.lz"
XatuBackpic::         INCBIN "gfx/pokemon/monback/xatub.2bpp.lz"
MareepFrontpic::      INCBIN "gfx/pokemon/gmon/mareep.2bpp.lz"
MareepBackpic::       INCBIN "gfx/pokemon/monback/mareepb.2bpp.lz"
FlaaffyFrontpic::     INCBIN "gfx/pokemon/gmon/flaaffy.2bpp.lz"
FlaaffyBackpic::      INCBIN "gfx/pokemon/monback/flaaffyb.2bpp.lz"
AmpharosFrontpic::    INCBIN "gfx/pokemon/gmon/ampharos.2bpp.lz"
AmpharosBackpic::     INCBIN "gfx/pokemon/monback/ampharosb.2bpp.lz"
BellossomFrontpic::   INCBIN "gfx/pokemon/gmon/bellossom.2bpp.lz"
BellossomBackpic::    INCBIN "gfx/pokemon/monback/bellossomb.2bpp.lz"
MarillFrontpic::      INCBIN "gfx/pokemon/gmon/marill.2bpp.lz"
MarillBackpic::       INCBIN "gfx/pokemon/monback/marillb.2bpp.lz"
AzumarillFrontpic::   INCBIN "gfx/pokemon/gmon/azumarill.2bpp.lz"
AzumarillBackpic::    INCBIN "gfx/pokemon/monback/azumarillb.2bpp.lz"
SudowoodoFrontpic::   INCBIN "gfx/pokemon/gmon/sudowoodo.2bpp.lz"
SudowoodoBackpic::    INCBIN "gfx/pokemon/monback/sudowoodob.2bpp.lz"
PolitoedFrontpic::    INCBIN "gfx/pokemon/gmon/politoed.2bpp.lz"
PolitoedBackpic::     INCBIN "gfx/pokemon/monback/politoedb.2bpp.lz"
HoppipFrontpic::      INCBIN "gfx/pokemon/gmon/hoppip.2bpp.lz"
HoppipBackpic::       INCBIN "gfx/pokemon/monback/hoppipb.2bpp.lz"
SkiploomFrontpic::    INCBIN "gfx/pokemon/gmon/skiploom.2bpp.lz"
SkiploomBackpic::     INCBIN "gfx/pokemon/monback/skiploomb.2bpp.lz"
JumpluffFrontpic::    INCBIN "gfx/pokemon/gmon/jumpluff.2bpp.lz"
JumpluffBackpic::     INCBIN "gfx/pokemon/monback/jumpluffb.2bpp.lz"
AipomFrontpic::       INCBIN "gfx/pokemon/gmon/aipom.2bpp.lz"
AipomBackpic::        INCBIN "gfx/pokemon/monback/aipomb.2bpp.lz"
SunkernFrontpic::     INCBIN "gfx/pokemon/gmon/sunkern.2bpp.lz"
SunkernBackpic::      INCBIN "gfx/pokemon/monback/sunkernb.2bpp.lz"
SunfloraFrontpic::    INCBIN "gfx/pokemon/gmon/sunflora.2bpp.lz"
SunfloraBackpic::     INCBIN "gfx/pokemon/monback/sunflorab.2bpp.lz"
YanmaFrontpic::       INCBIN "gfx/pokemon/gmon/yanma.2bpp.lz"
YanmaBackpic::        INCBIN "gfx/pokemon/monback/yanmab.2bpp.lz"
WooperFrontpic::      INCBIN "gfx/pokemon/gmon/wooper.2bpp.lz"
WooperBackpic::       INCBIN "gfx/pokemon/monback/wooperb.2bpp.lz"


SECTION "Pics 10", ROMX

QuagsireFrontpic::    INCBIN "gfx/pokemon/gmon/quagsire.2bpp.lz"
QuagsireBackpic::     INCBIN "gfx/pokemon/monback/quagsireb.2bpp.lz"
EspeonFrontpic::      INCBIN "gfx/pokemon/gmon/espeon.2bpp.lz"
EspeonBackpic::       INCBIN "gfx/pokemon/monback/espeonb.2bpp.lz"
UmbreonFrontpic::     INCBIN "gfx/pokemon/gmon/umbreon.2bpp.lz"
UmbreonBackpic::      INCBIN "gfx/pokemon/monback/umbreonb.2bpp.lz"
MurkrowFrontpic::     INCBIN "gfx/pokemon/gmon/murkrow.2bpp.lz"
MurkrowBackpic::      INCBIN "gfx/pokemon/monback/murkrowb.2bpp.lz"
SlowkingFrontpic::    INCBIN "gfx/pokemon/gmon/slowking.2bpp.lz"
SlowkingBackpic::     INCBIN "gfx/pokemon/monback/slowkingb.2bpp.lz"
MisdreavusFrontpic::  INCBIN "gfx/pokemon/gmon/misdreavus.2bpp.lz"
MisdreavusBackpic::   INCBIN "gfx/pokemon/monback/misdreavusb.2bpp.lz"
WobbuffetFrontpic::   INCBIN "gfx/pokemon/gmon/wobbuffet.2bpp.lz"
WobbuffetBackpic::    INCBIN "gfx/pokemon/monback/wobbuffetb.2bpp.lz"
GirafarigFrontpic::   INCBIN "gfx/pokemon/gmon/girafarig.2bpp.lz"
GirafarigBackpic::    INCBIN "gfx/pokemon/monback/girafarigb.2bpp.lz"
PinecoFrontpic::      INCBIN "gfx/pokemon/gmon/pineco.2bpp.lz"
PinecoBackpic::       INCBIN "gfx/pokemon/monback/pinecob.2bpp.lz"
ForretressFrontpic::  INCBIN "gfx/pokemon/gmon/forretress.2bpp.lz"
ForretressBackpic::   INCBIN "gfx/pokemon/monback/forretressb.2bpp.lz"
DunsparceFrontpic::   INCBIN "gfx/pokemon/gmon/dunsparce.2bpp.lz"
DunsparceBackpic::    INCBIN "gfx/pokemon/monback/dunsparceb.2bpp.lz"
GligarFrontpic::      INCBIN "gfx/pokemon/gmon/gligar.2bpp.lz"
GligarBackpic::       INCBIN "gfx/pokemon/monback/gligarb.2bpp.lz"
SteelixFrontpic::     INCBIN "gfx/pokemon/gmon/steelix.2bpp.lz"
SteelixBackpic::      INCBIN "gfx/pokemon/monback/steelixb.2bpp.lz"
SnubbullFrontpic::    INCBIN "gfx/pokemon/gmon/snubbull.2bpp.lz"
SnubbullBackpic::     INCBIN "gfx/pokemon/monback/snubbullb.2bpp.lz"
GranbullFrontpic::    INCBIN "gfx/pokemon/gmon/granbull.2bpp.lz"
GranbullBackpic::     INCBIN "gfx/pokemon/monback/granbullb.2bpp.lz"
QwilfishFrontpic::    INCBIN "gfx/pokemon/gmon/qwilfish.2bpp.lz"
QwilfishBackpic::     INCBIN "gfx/pokemon/monback/qwilfishb.2bpp.lz"
ScizorFrontpic::      INCBIN "gfx/pokemon/gmon/scizor.2bpp.lz"
ScizorBackpic::       INCBIN "gfx/pokemon/monback/scizorb.2bpp.lz"
ShuckleFrontpic::     INCBIN "gfx/pokemon/gmon/shuckle.2bpp.lz"
ShuckleBackpic::      INCBIN "gfx/pokemon/monback/shuckleb.2bpp.lz"
HeracrossFrontpic::   INCBIN "gfx/pokemon/gmon/heracross.2bpp.lz"
HeracrossBackpic::    INCBIN "gfx/pokemon/monback/heracrossb.2bpp.lz"
SneaselFrontpic::     INCBIN "gfx/pokemon/gmon/sneasel.2bpp.lz"
SneaselBackpic::      INCBIN "gfx/pokemon/monback/sneaselb.2bpp.lz"
TeddiursaFrontpic::   INCBIN "gfx/pokemon/gmon/teddiursa.2bpp.lz"
TeddiursaBackpic::    INCBIN "gfx/pokemon/monback/teddiursab.2bpp.lz"
UrsaringFrontpic::    INCBIN "gfx/pokemon/gmon/ursaring.2bpp.lz"
UrsaringBackpic::     INCBIN "gfx/pokemon/monback/ursaringb.2bpp.lz"


SECTION "Pics 11", ROMX

SlugmaFrontpic::      INCBIN "gfx/pokemon/gmon/slugma.2bpp.lz"
SlugmaBackpic::       INCBIN "gfx/pokemon/monback/slugmab.2bpp.lz"
MagcargoFrontpic::    INCBIN "gfx/pokemon/gmon/magcargo.2bpp.lz"
MagcargoBackpic::     INCBIN "gfx/pokemon/monback/magcargob.2bpp.lz"
SwinubFrontpic::      INCBIN "gfx/pokemon/gmon/swinub.2bpp.lz"
SwinubBackpic::       INCBIN "gfx/pokemon/monback/swinubb.2bpp.lz"
PiloswineFrontpic::   INCBIN "gfx/pokemon/gmon/piloswine.2bpp.lz"
PiloswineBackpic::    INCBIN "gfx/pokemon/monback/piloswineb.2bpp.lz"
CorsolaFrontpic::     INCBIN "gfx/pokemon/gmon/corsola.2bpp.lz"
CorsolaBackpic::      INCBIN "gfx/pokemon/monback/corsolab.2bpp.lz"
RemoraidFrontpic::    INCBIN "gfx/pokemon/gmon/remoraid.2bpp.lz"
RemoraidBackpic::     INCBIN "gfx/pokemon/monback/remoraidb.2bpp.lz"
OctilleryFrontpic::   INCBIN "gfx/pokemon/gmon/octillery.2bpp.lz"
OctilleryBackpic::    INCBIN "gfx/pokemon/monback/octilleryb.2bpp.lz"
DelibirdFrontpic::    INCBIN "gfx/pokemon/gmon/delibird.2bpp.lz"
DelibirdBackpic::     INCBIN "gfx/pokemon/monback/delibirdb.2bpp.lz"
MantineFrontpic::     INCBIN "gfx/pokemon/gmon/mantine.2bpp.lz"
MantineBackpic::      INCBIN "gfx/pokemon/monback/mantineb.2bpp.lz"
SkarmoryFrontpic::    INCBIN "gfx/pokemon/gmon/skarmory.2bpp.lz"
SkarmoryBackpic::     INCBIN "gfx/pokemon/monback/skarmoryb.2bpp.lz"
HoundourFrontpic::    INCBIN "gfx/pokemon/gmon/houndour.2bpp.lz"
HoundourBackpic::     INCBIN "gfx/pokemon/monback/houndourb.2bpp.lz"
HoundoomFrontpic::    INCBIN "gfx/pokemon/gmon/houndoom.2bpp.lz"
HoundoomBackpic::     INCBIN "gfx/pokemon/monback/houndoomb.2bpp.lz"
KingdraFrontpic::     INCBIN "gfx/pokemon/gmon/kingdra.2bpp.lz"
KingdraBackpic::      INCBIN "gfx/pokemon/monback/kingdrab.2bpp.lz"
PhanpyFrontpic::      INCBIN "gfx/pokemon/gmon/phanpy.2bpp.lz"
PhanpyBackpic::       INCBIN "gfx/pokemon/monback/phanpyb.2bpp.lz"
DonphanFrontpic::     INCBIN "gfx/pokemon/gmon/donphan.2bpp.lz"
DonphanBackpic::      INCBIN "gfx/pokemon/monback/donphanb.2bpp.lz"
Porygon2Frontpic::    INCBIN "gfx/pokemon/gmon/porygon2.2bpp.lz"
Porygon2Backpic::     INCBIN "gfx/pokemon/monback/porygon2b.2bpp.lz"
StantlerFrontpic::    INCBIN "gfx/pokemon/gmon/stantler.2bpp.lz"
StantlerBackpic::     INCBIN "gfx/pokemon/monback/stantlerb.2bpp.lz"
SmeargleFrontpic::    INCBIN "gfx/pokemon/gmon/smeargle.2bpp.lz"
SmeargleBackpic::     INCBIN "gfx/pokemon/monback/smeargleb.2bpp.lz"
TyrogueFrontpic::     INCBIN "gfx/pokemon/gmon/tyrogue.2bpp.lz"
TyrogueBackpic::      INCBIN "gfx/pokemon/monback/tyrogueb.2bpp.lz"
HitmontopFrontpic::   INCBIN "gfx/pokemon/gmon/hitmontop.2bpp.lz"
HitmontopBackpic::    INCBIN "gfx/pokemon/monback/hitmontopb.2bpp.lz"
SmoochumFrontpic::    INCBIN "gfx/pokemon/gmon/smoochum.2bpp.lz"
SmoochumBackpic::     INCBIN "gfx/pokemon/monback/smoochumb.2bpp.lz"


SECTION "Pics 12", ROMX

ElekidFrontpic::      INCBIN "gfx/pokemon/gmon/elekid.2bpp.lz"
ElekidBackpic::       INCBIN "gfx/pokemon/monback/elekidb.2bpp.lz"
MagbyFrontpic::       INCBIN "gfx/pokemon/gmon/magby.2bpp.lz"
MagbyBackpic::        INCBIN "gfx/pokemon/monback/magbyb.2bpp.lz"
MiltankFrontpic::     INCBIN "gfx/pokemon/gmon/miltank.2bpp.lz"
MiltankBackpic::      INCBIN "gfx/pokemon/monback/miltankb.2bpp.lz"
BlisseyFrontpic::     INCBIN "gfx/pokemon/gmon/blissey.2bpp.lz"
BlisseyBackpic::      INCBIN "gfx/pokemon/monback/blisseyb.2bpp.lz"
RaikouFrontpic::      INCBIN "gfx/pokemon/gmon/raikou.2bpp.lz"
RaikouBackpic::       INCBIN "gfx/pokemon/monback/raikoub.2bpp.lz"
EnteiFrontpic::       INCBIN "gfx/pokemon/gmon/entei.2bpp.lz"
EnteiBackpic::        INCBIN "gfx/pokemon/monback/enteib.2bpp.lz"
SuicuneFrontpic::     INCBIN "gfx/pokemon/gmon/suicune.2bpp.lz"
SuicuneBackpic::      INCBIN "gfx/pokemon/monback/suicuneb.2bpp.lz"
LarvitarFrontpic::    INCBIN "gfx/pokemon/gmon/larvitar.2bpp.lz"
LarvitarBackpic::     INCBIN "gfx/pokemon/monback/larvitarb.2bpp.lz"
PupitarFrontpic::     INCBIN "gfx/pokemon/gmon/pupitar.2bpp.lz"
PupitarBackpic::      INCBIN "gfx/pokemon/monback/pupitarb.2bpp.lz"
TyranitarFrontpic::   INCBIN "gfx/pokemon/gmon/tyranitar.2bpp.lz"
TyranitarBackpic::    INCBIN "gfx/pokemon/monback/tyranitarb.2bpp.lz"
LugiaFrontpic::       INCBIN "gfx/pokemon/gmon/lugia.2bpp.lz"
LugiaBackpic::        INCBIN "gfx/pokemon/monback/lugiab.2bpp.lz"
HoOhFrontpic::        INCBIN "gfx/pokemon/gmon/hooh.2bpp.lz"
HoOhBackpic::         INCBIN "gfx/pokemon/monback/hoohb.2bpp.lz"
CelebiFrontpic::      INCBIN "gfx/pokemon/gmon/celebi.2bpp.lz"
CelebiBackpic::       INCBIN "gfx/pokemon/monback/celebib.2bpp.lz"
EggPic::              INCBIN "gfx/pokemon/gmon/egg.2bpp.lz"


SECTION "Pics 13", ROMX

UnownAFrontpic::      INCBIN "gfx/pokemon/unown/unowna.2bpp.lz"
UnownABackpic::       INCBIN "gfx/pokemon/unownback/unowna.2bpp.lz"
UnownBFrontpic::      INCBIN "gfx/pokemon/unown/unownb.2bpp.lz"
UnownBBackpic::       INCBIN "gfx/pokemon/unownback/unownb.2bpp.lz"
UnownCFrontpic::      INCBIN "gfx/pokemon/unown/unownc.2bpp.lz"
UnownCBackpic::       INCBIN "gfx/pokemon/unownback/unownc.2bpp.lz"
UnownDFrontpic::      INCBIN "gfx/pokemon/unown/unownd.2bpp.lz"
UnownDBackpic::       INCBIN "gfx/pokemon/unownback/unownd.2bpp.lz"
UnownEFrontpic::      INCBIN "gfx/pokemon/unown/unowne.2bpp.lz"
UnownEBackpic::       INCBIN "gfx/pokemon/unownback/unowne.2bpp.lz"
UnownFFrontpic::      INCBIN "gfx/pokemon/unown/unownf.2bpp.lz"
UnownFBackpic::       INCBIN "gfx/pokemon/unownback/unownf.2bpp.lz"
UnownGFrontpic::      INCBIN "gfx/pokemon/unown/unowng.2bpp.lz"
UnownGBackpic::       INCBIN "gfx/pokemon/unownback/unowng.2bpp.lz"
UnownHFrontpic::      INCBIN "gfx/pokemon/unown/unownh.2bpp.lz"
UnownHBackpic::       INCBIN "gfx/pokemon/unownback/unownh.2bpp.lz"
UnownIFrontpic::      INCBIN "gfx/pokemon/unown/unowni.2bpp.lz"
UnownIBackpic::       INCBIN "gfx/pokemon/unownback/unowni.2bpp.lz"
UnownJFrontpic::      INCBIN "gfx/pokemon/unown/unownj.2bpp.lz"
UnownJBackpic::       INCBIN "gfx/pokemon/unownback/unownj.2bpp.lz"
UnownKFrontpic::      INCBIN "gfx/pokemon/unown/unownk.2bpp.lz"
UnownKBackpic::       INCBIN "gfx/pokemon/unownback/unownk.2bpp.lz"
UnownLFrontpic::      INCBIN "gfx/pokemon/unown/unownl.2bpp.lz"
UnownLBackpic::       INCBIN "gfx/pokemon/unownback/unownl.2bpp.lz"
UnownMFrontpic::      INCBIN "gfx/pokemon/unown/unownm.2bpp.lz"
UnownMBackpic::       INCBIN "gfx/pokemon/unownback/unownm.2bpp.lz"
UnownNFrontpic::      INCBIN "gfx/pokemon/unown/unownn.2bpp.lz"
UnownNBackpic::       INCBIN "gfx/pokemon/unownback/unownn.2bpp.lz"
UnownOFrontpic::      INCBIN "gfx/pokemon/unown/unowno.2bpp.lz"
UnownOBackpic::       INCBIN "gfx/pokemon/unownback/unowno.2bpp.lz"
UnownPFrontpic::      INCBIN "gfx/pokemon/unown/unownp.2bpp.lz"
UnownPBackpic::       INCBIN "gfx/pokemon/unownback/unownp.2bpp.lz"
UnownQFrontpic::      INCBIN "gfx/pokemon/unown/unownq.2bpp.lz"
UnownQBackpic::       INCBIN "gfx/pokemon/unownback/unownq.2bpp.lz"
UnownRFrontpic::      INCBIN "gfx/pokemon/unown/unownr.2bpp.lz"
UnownRBackpic::       INCBIN "gfx/pokemon/unownback/unownr.2bpp.lz"
UnownSFrontpic::      INCBIN "gfx/pokemon/unown/unowns.2bpp.lz"
UnownSBackpic::       INCBIN "gfx/pokemon/unownback/unowns.2bpp.lz"
UnownTFrontpic::      INCBIN "gfx/pokemon/unown/unownt.2bpp.lz"
UnownTBackpic::       INCBIN "gfx/pokemon/unownback/unownt.2bpp.lz"
UnownUFrontpic::      INCBIN "gfx/pokemon/unown/unownu.2bpp.lz"
UnownUBackpic::       INCBIN "gfx/pokemon/unownback/unownu.2bpp.lz"
UnownVFrontpic::      INCBIN "gfx/pokemon/unown/unownv.2bpp.lz"
UnownVBackpic::       INCBIN "gfx/pokemon/unownback/unownv.2bpp.lz"
UnownWFrontpic::      INCBIN "gfx/pokemon/unown/unownw.2bpp.lz"
UnownWBackpic::       INCBIN "gfx/pokemon/unownback/unownw.2bpp.lz"
UnownXFrontpic::      INCBIN "gfx/pokemon/unown/unownx.2bpp.lz"
UnownXBackpic::       INCBIN "gfx/pokemon/unownback/unownx.2bpp.lz"
UnownYFrontpic::      INCBIN "gfx/pokemon/unown/unowny.2bpp.lz"
UnownYBackpic::       INCBIN "gfx/pokemon/unownback/unowny.2bpp.lz"
UnownZFrontpic::      INCBIN "gfx/pokemon/unown/unownz.2bpp.lz"
UnownZBackpic::       INCBIN "gfx/pokemon/unownback/unownz.2bpp.lz"


SECTION "Pics 14", ROMX

PokemonProfPic::      INCBIN "gfx/trainers/oak.2bpp.lz"
HiroBattlePic::       INCBIN "gfx/player/hiro.2bpp.lz"
SylviaBattlePic::     INCBIN "gfx/player/sylvia.2bpp.lz"
Rival1Pic::           INCBIN "gfx/trainers/rival1.2bpp.lz"
