INCLUDE "constants.asm"


; PokemonPicPointers and UnownPicPointers are assumed to start at the same
; address, but in different banks. This is enforced in layout.link.


SECTION "Pic Pointers", ROMX

INCLUDE "data/pokemon/pic_pointers.asm"


SECTION "Unown Pic Pointers", ROMX

INCLUDE "data/pokemon/unown_pic_pointers.asm"


SECTION "Trainer Pic Pointers", ROMX

INCLUDE "data/trainers/pic_pointers.asm"


; Pokémon pics

SECTION "Pics 1", ROMX

BulbasaurFrontpic::     INCBIN "gfx/pokemon/monfront/bulbasaur.2bpp.lz"
BulbasaurBackpic::      INCBIN "gfx/pokemon/monback/bulbasaurb.2bpp.lz"
IvysaurFrontpic::       INCBIN "gfx/pokemon/monfront/ivysaur.2bpp.lz"
IvysaurBackpic::        INCBIN "gfx/pokemon/monback/ivysaurb.2bpp.lz"
VenusaurFrontpic::      INCBIN "gfx/pokemon/monfront/venusaur.2bpp.lz"
VenusaurBackpic::       INCBIN "gfx/pokemon/monback/venusaurb.2bpp.lz"
CharmanderFrontpic::    INCBIN "gfx/pokemon/monfront/charmander.2bpp.lz"
CharmanderBackpic::     INCBIN "gfx/pokemon/monback/charmanderb.2bpp.lz"
CharmeleonFrontpic::    INCBIN "gfx/pokemon/monfront/charmeleon.2bpp.lz"
CharmeleonBackpic::     INCBIN "gfx/pokemon/monback/charmeleonb.2bpp.lz"
CharizardFrontpic::     INCBIN "gfx/pokemon/monfront/charizard.2bpp.lz"
CharizardBackpic::      INCBIN "gfx/pokemon/monback/charizardb.2bpp.lz"
SquirtleFrontpic::      INCBIN "gfx/pokemon/monfront/squirtle.2bpp.lz"
SquirtleBackpic::       INCBIN "gfx/pokemon/monback/squirtleb.2bpp.lz"
WartortleFrontpic::     INCBIN "gfx/pokemon/monfront/wartortle.2bpp.lz"
WartortleBackpic::      INCBIN "gfx/pokemon/monback/wartortleb.2bpp.lz"
BlastoiseFrontpic::     INCBIN "gfx/pokemon/monfront/blastoise.2bpp.lz"
BlastoiseBackpic::      INCBIN "gfx/pokemon/monback/blastoiseb.2bpp.lz"
CaterpieFrontpic::      INCBIN "gfx/pokemon/monfront/caterpie.2bpp.lz"
CaterpieBackpic::       INCBIN "gfx/pokemon/monback/caterpieb.2bpp.lz"
MetapodFrontpic::       INCBIN "gfx/pokemon/monfront/metapod.2bpp.lz"
MetapodBackpic::        INCBIN "gfx/pokemon/monback/metapodb.2bpp.lz"
ButterfreeFrontpic::    INCBIN "gfx/pokemon/monfront/butterfree.2bpp.lz"
ButterfreeBackpic::     INCBIN "gfx/pokemon/monback/butterfreeb.2bpp.lz"
WeedleFrontpic::        INCBIN "gfx/pokemon/monfront/weedle.2bpp.lz"
WeedleBackpic::         INCBIN "gfx/pokemon/monback/weedleb.2bpp.lz"
KakunaFrontpic::        INCBIN "gfx/pokemon/monfront/kakuna.2bpp.lz"
KakunaBackpic::         INCBIN "gfx/pokemon/monback/kakunab.2bpp.lz"
BeedrillFrontpic::      INCBIN "gfx/pokemon/monfront/beedrill.2bpp.lz"
BeedrillBackpic::       INCBIN "gfx/pokemon/monback/beedrillb.2bpp.lz"
PidgeyFrontpic::        INCBIN "gfx/pokemon/monfront/pidgey.2bpp.lz"
PidgeyBackpic::         INCBIN "gfx/pokemon/monback/pidgeyb.2bpp.lz"
PidgeottoFrontpic::     INCBIN "gfx/pokemon/monfront/pidgeotto.2bpp.lz"
PidgeottoBackpic::      INCBIN "gfx/pokemon/monback/pidgeottob.2bpp.lz"
PidgeotFrontpic::       INCBIN "gfx/pokemon/monfront/pidgeot.2bpp.lz"
PidgeotBackpic::        INCBIN "gfx/pokemon/monback/pidgeotb.2bpp.lz"
RattataFrontpic::       INCBIN "gfx/pokemon/monfront/rattata.2bpp.lz"
RattataBackpic::        INCBIN "gfx/pokemon/monback/rattatab.2bpp.lz"
RaticateFrontpic::      INCBIN "gfx/pokemon/monfront/raticate.2bpp.lz"
RaticateBackpic::       INCBIN "gfx/pokemon/monback/raticateb.2bpp.lz"
SpearowFrontpic::       INCBIN "gfx/pokemon/monfront/spearow.2bpp.lz"
SpearowBackpic::        INCBIN "gfx/pokemon/monback/spearowb.2bpp.lz"
FearowFrontpic::        INCBIN "gfx/pokemon/monfront/fearow.2bpp.lz"
FearowBackpic::         INCBIN "gfx/pokemon/monback/fearowb.2bpp.lz"


SECTION "Pics 2", ROMX

EkansFrontpic::         INCBIN "gfx/pokemon/monfront/ekans.2bpp.lz"
EkansBackpic::          INCBIN "gfx/pokemon/monback/ekansb.2bpp.lz"
ArbokFrontpic::         INCBIN "gfx/pokemon/monfront/arbok.2bpp.lz"
ArbokBackpic::          INCBIN "gfx/pokemon/monback/arbokb.2bpp.lz"
PikachuFrontpic::       INCBIN "gfx/pokemon/monfront/pikachu.2bpp.lz"
PikachuBackpic::        INCBIN "gfx/pokemon/monback/pikachub.2bpp.lz"
RaichuFrontpic::        INCBIN "gfx/pokemon/monfront/raichu.2bpp.lz"
RaichuBackpic::         INCBIN "gfx/pokemon/monback/raichub.2bpp.lz"
SandshrewFrontpic::     INCBIN "gfx/pokemon/monfront/sandshrew.2bpp.lz"
SandshrewBackpic::      INCBIN "gfx/pokemon/monback/sandshrewb.2bpp.lz"
SandslashFrontpic::     INCBIN "gfx/pokemon/monfront/sandslash.2bpp.lz"
SandslashBackpic::      INCBIN "gfx/pokemon/monback/sandslashb.2bpp.lz"
NidoranFFrontpic::      INCBIN "gfx/pokemon/monfront/nidoran_f.2bpp.lz"
NidoranFBackpic::       INCBIN "gfx/pokemon/monback/nidoranfb.2bpp.lz"
NidorinaFrontpic::      INCBIN "gfx/pokemon/monfront/nidorina.2bpp.lz"
NidorinaBackpic::       INCBIN "gfx/pokemon/monback/nidorinab.2bpp.lz"
NidoqueenFrontpic::     INCBIN "gfx/pokemon/monfront/nidoqueen.2bpp.lz"
NidoqueenBackpic::      INCBIN "gfx/pokemon/monback/nidoqueenb.2bpp.lz"
NidoranMFrontpic::      INCBIN "gfx/pokemon/monfront/nidoran_m.2bpp.lz"
NidoranMBackpic::       INCBIN "gfx/pokemon/monback/nidoranmb.2bpp.lz"
NidorinoFrontpic::      INCBIN "gfx/pokemon/monfront/nidorino.2bpp.lz"
NidorinoBackpic::       INCBIN "gfx/pokemon/monback/nidorinob.2bpp.lz"
NidokingFrontpic::      INCBIN "gfx/pokemon/monfront/nidoking.2bpp.lz"
NidokingBackpic::       INCBIN "gfx/pokemon/monback/nidokingb.2bpp.lz"
ClefairyFrontpic::      INCBIN "gfx/pokemon/monfront/clefairy.2bpp.lz"
ClefairyBackpic::       INCBIN "gfx/pokemon/monback/clefairyb.2bpp.lz"
ClefableFrontpic::      INCBIN "gfx/pokemon/monfront/clefable.2bpp.lz"
ClefableBackpic::       INCBIN "gfx/pokemon/monback/clefableb.2bpp.lz"
VulpixFrontpic::        INCBIN "gfx/pokemon/monfront/vulpix.2bpp.lz"
VulpixBackpic::         INCBIN "gfx/pokemon/monback/vulpixb.2bpp.lz"
NinetalesFrontpic::     INCBIN "gfx/pokemon/monfront/ninetales.2bpp.lz"
NinetalesBackpic::      INCBIN "gfx/pokemon/monback/ninetalesb.2bpp.lz"
JigglypuffFrontpic::    INCBIN "gfx/pokemon/monfront/jigglypuff.2bpp.lz"
JigglypuffBackpic::     INCBIN "gfx/pokemon/monback/jigglypuffb.2bpp.lz"
WigglytuffFrontpic::    INCBIN "gfx/pokemon/monfront/wigglytuff.2bpp.lz"
WigglytuffBackpic::     INCBIN "gfx/pokemon/monback/wigglytuffb.2bpp.lz"
ZubatFrontpic::         INCBIN "gfx/pokemon/monfront/zubat.2bpp.lz"
ZubatBackpic::          INCBIN "gfx/pokemon/monback/zubatb.2bpp.lz"
GolbatFrontpic::        INCBIN "gfx/pokemon/monfront/golbat.2bpp.lz"
GolbatBackpic::         INCBIN "gfx/pokemon/monback/golbatb.2bpp.lz"
OddishFrontpic::        INCBIN "gfx/pokemon/monfront/oddish.2bpp.lz"
OddishBackpic::         INCBIN "gfx/pokemon/monback/oddishb.2bpp.lz"
GloomFrontpic::         INCBIN "gfx/pokemon/monfront/gloom.2bpp.lz"
GloomBackpic::          INCBIN "gfx/pokemon/monback/gloomb.2bpp.lz"


SECTION "Pics 3", ROMX

VileplumeFrontpic::     INCBIN "gfx/pokemon/monfront/vileplume.2bpp.lz"
VileplumeBackpic::      INCBIN "gfx/pokemon/monback/vileplumeb.2bpp.lz"
ParasFrontpic::         INCBIN "gfx/pokemon/monfront/paras.2bpp.lz"
ParasBackpic::          INCBIN "gfx/pokemon/monback/parasb.2bpp.lz"
ParasectFrontpic::      INCBIN "gfx/pokemon/monfront/parasect.2bpp.lz"
ParasectBackpic::       INCBIN "gfx/pokemon/monback/parasectb.2bpp.lz"
VenonatFrontpic::       INCBIN "gfx/pokemon/monfront/venonat.2bpp.lz"
VenonatBackpic::        INCBIN "gfx/pokemon/monback/venonatb.2bpp.lz"
VenomothFrontpic::      INCBIN "gfx/pokemon/monfront/venomoth.2bpp.lz"
VenomothBackpic::       INCBIN "gfx/pokemon/monback/venomothb.2bpp.lz"
DiglettFrontpic::       INCBIN "gfx/pokemon/monfront/diglett.2bpp.lz"
DiglettBackpic::        INCBIN "gfx/pokemon/monback/diglettb.2bpp.lz"
DugtrioFrontpic::       INCBIN "gfx/pokemon/monfront/dugtrio.2bpp.lz"
DugtrioBackpic::        INCBIN "gfx/pokemon/monback/dugtriob.2bpp.lz"
MeowthFrontpic::        INCBIN "gfx/pokemon/monfront/meowth.2bpp.lz"
MeowthBackpic::         INCBIN "gfx/pokemon/monback/meowthb.2bpp.lz"
PersianFrontpic::       INCBIN "gfx/pokemon/monfront/persian.2bpp.lz"
PersianBackpic::        INCBIN "gfx/pokemon/monback/persianb.2bpp.lz"
PsyduckFrontpic::       INCBIN "gfx/pokemon/monfront/psyduck.2bpp.lz"
PsyduckBackpic::        INCBIN "gfx/pokemon/monback/psyduckb.2bpp.lz"
GolduckFrontpic::       INCBIN "gfx/pokemon/monfront/golduck.2bpp.lz"
GolduckBackpic::        INCBIN "gfx/pokemon/monback/golduckb.2bpp.lz"
MankeyFrontpic::        INCBIN "gfx/pokemon/monfront/mankey.2bpp.lz"
MankeyBackpic::         INCBIN "gfx/pokemon/monback/mankeyb.2bpp.lz"
PrimeapeFrontpic::      INCBIN "gfx/pokemon/monfront/primeape.2bpp.lz"
PrimeapeBackpic::       INCBIN "gfx/pokemon/monback/primeapeb.2bpp.lz"
GrowlitheFrontpic::     INCBIN "gfx/pokemon/monfront/growlithe.2bpp.lz"
GrowlitheBackpic::      INCBIN "gfx/pokemon/monback/growlitheb.2bpp.lz"
ArcanineFrontpic::      INCBIN "gfx/pokemon/monfront/arcanine.2bpp.lz"
ArcanineBackpic::       INCBIN "gfx/pokemon/monback/arcanineb.2bpp.lz"
PoliwagFrontpic::       INCBIN "gfx/pokemon/monfront/poliwag.2bpp.lz"
PoliwagBackpic::        INCBIN "gfx/pokemon/monback/poliwagb.2bpp.lz"
PoliwhirlFrontpic::     INCBIN "gfx/pokemon/monfront/poliwhirl.2bpp.lz"
PoliwhirlBackpic::      INCBIN "gfx/pokemon/monback/poliwhirlb.2bpp.lz"
PoliwrathFrontpic::     INCBIN "gfx/pokemon/monfront/poliwrath.2bpp.lz"
PoliwrathBackpic::      INCBIN "gfx/pokemon/monback/poliwrathb.2bpp.lz"
AbraFrontpic::          INCBIN "gfx/pokemon/monfront/abra.2bpp.lz"
AbraBackpic::           INCBIN "gfx/pokemon/monback/abrab.2bpp.lz"
KadabraFrontpic::       INCBIN "gfx/pokemon/monfront/kadabra.2bpp.lz"
KadabraBackpic::        INCBIN "gfx/pokemon/monback/kadabrab.2bpp.lz"
AlakazamFrontpic::      INCBIN "gfx/pokemon/monfront/alakazam.2bpp.lz"
AlakazamBackpic::       INCBIN "gfx/pokemon/monback/alakazamb.2bpp.lz"


SECTION "Pics 4", ROMX

MachopFrontpic::        INCBIN "gfx/pokemon/monfront/machop.2bpp.lz"
MachopBackpic::         INCBIN "gfx/pokemon/monback/machopb.2bpp.lz"
MachokeFrontpic::       INCBIN "gfx/pokemon/monfront/machoke.2bpp.lz"
MachokeBackpic::        INCBIN "gfx/pokemon/monback/machokeb.2bpp.lz"
MachampFrontpic::       INCBIN "gfx/pokemon/monfront/machamp.2bpp.lz"
MachampBackpic::        INCBIN "gfx/pokemon/monback/machampb.2bpp.lz"
BellsproutFrontpic::    INCBIN "gfx/pokemon/monfront/bellsprout.2bpp.lz"
BellsproutBackpic::     INCBIN "gfx/pokemon/monback/bellsproutb.2bpp.lz"
WeepinbellFrontpic::    INCBIN "gfx/pokemon/monfront/weepinbell.2bpp.lz"
WeepinbellBackpic::     INCBIN "gfx/pokemon/monback/weepinbellb.2bpp.lz"
VictreebelFrontpic::    INCBIN "gfx/pokemon/monfront/victreebel.2bpp.lz"
VictreebelBackpic::     INCBIN "gfx/pokemon/monback/victreebelb.2bpp.lz"
TentacoolFrontpic::     INCBIN "gfx/pokemon/monfront/tentacool.2bpp.lz"
TentacoolBackpic::      INCBIN "gfx/pokemon/monback/tentacoolb.2bpp.lz"
TentacruelFrontpic::    INCBIN "gfx/pokemon/monfront/tentacruel.2bpp.lz"
TentacruelBackpic::     INCBIN "gfx/pokemon/monback/tentacruelb.2bpp.lz"
GeodudeFrontpic::       INCBIN "gfx/pokemon/monfront/geodude.2bpp.lz"
GeodudeBackpic::        INCBIN "gfx/pokemon/monback/geodudeb.2bpp.lz"
GravelerFrontpic::      INCBIN "gfx/pokemon/monfront/graveler.2bpp.lz"
GravelerBackpic::       INCBIN "gfx/pokemon/monback/gravelerb.2bpp.lz"
GolemFrontpic::         INCBIN "gfx/pokemon/monfront/golem.2bpp.lz"
GolemBackpic::          INCBIN "gfx/pokemon/monback/golemb.2bpp.lz"
PonytaFrontpic::        INCBIN "gfx/pokemon/monfront/ponyta.2bpp.lz"
PonytaBackpic::         INCBIN "gfx/pokemon/monback/ponytab.2bpp.lz"
RapidashFrontpic::      INCBIN "gfx/pokemon/monfront/rapidash.2bpp.lz"
RapidashBackpic::       INCBIN "gfx/pokemon/monback/rapidashb.2bpp.lz"
SlowpokeFrontpic::      INCBIN "gfx/pokemon/monfront/slowpoke.2bpp.lz"
SlowpokeBackpic::       INCBIN "gfx/pokemon/monback/slowpokeb.2bpp.lz"
SlowbroFrontpic::       INCBIN "gfx/pokemon/monfront/slowbro.2bpp.lz"
SlowbroBackpic::        INCBIN "gfx/pokemon/monback/slowbrob.2bpp.lz"
MagnemiteFrontpic::     INCBIN "gfx/pokemon/monfront/magnemite.2bpp.lz"
MagnemiteBackpic::      INCBIN "gfx/pokemon/monback/magnemiteb.2bpp.lz"
MagnetonFrontpic::      INCBIN "gfx/pokemon/monfront/magneton.2bpp.lz"
MagnetonBackpic::       INCBIN "gfx/pokemon/monback/magnetonb.2bpp.lz"
FarfetchDFrontpic::     INCBIN "gfx/pokemon/monfront/farfetch_d.2bpp.lz"
FarfetchDBackpic::      INCBIN "gfx/pokemon/monback/farfetchdb.2bpp.lz"
DoduoFrontpic::         INCBIN "gfx/pokemon/monfront/doduo.2bpp.lz"
DoduoBackpic::          INCBIN "gfx/pokemon/monback/doduob.2bpp.lz"
DodrioFrontpic::        INCBIN "gfx/pokemon/monfront/dodrio.2bpp.lz"
DodrioBackpic::         INCBIN "gfx/pokemon/monback/dodriob.2bpp.lz"
SeelFrontpic::          INCBIN "gfx/pokemon/monfront/seel.2bpp.lz"
SeelBackpic::           INCBIN "gfx/pokemon/monback/seelb.2bpp.lz"


SECTION "Pics 5", ROMX

DewgongFrontpic::       INCBIN "gfx/pokemon/monfront/dewgong.2bpp.lz"
DewgongBackpic::        INCBIN "gfx/pokemon/monback/dewgongb.2bpp.lz"
GrimerFrontpic::        INCBIN "gfx/pokemon/monfront/grimer.2bpp.lz"
GrimerBackpic::         INCBIN "gfx/pokemon/monback/grimerb.2bpp.lz"
MukFrontpic::           INCBIN "gfx/pokemon/monfront/muk.2bpp.lz"
MukBackpic::            INCBIN "gfx/pokemon/monback/mukb.2bpp.lz"
ShellderFrontpic::      INCBIN "gfx/pokemon/monfront/shellder.2bpp.lz"
ShellderBackpic::       INCBIN "gfx/pokemon/monback/shellderb.2bpp.lz"
CloysterFrontpic::      INCBIN "gfx/pokemon/monfront/cloyster.2bpp.lz"
CloysterBackpic::       INCBIN "gfx/pokemon/monback/cloysterb.2bpp.lz"
GastlyFrontpic::        INCBIN "gfx/pokemon/monfront/gastly.2bpp.lz"
GastlyBackpic::         INCBIN "gfx/pokemon/monback/gastlyb.2bpp.lz"
HaunterFrontpic::       INCBIN "gfx/pokemon/monfront/haunter.2bpp.lz"
HaunterBackpic::        INCBIN "gfx/pokemon/monback/haunterb.2bpp.lz"
GengarFrontpic::        INCBIN "gfx/pokemon/monfront/gengar.2bpp.lz"
GengarBackpic::         INCBIN "gfx/pokemon/monback/gengarb.2bpp.lz"
OnixFrontpic::          INCBIN "gfx/pokemon/monfront/onix.2bpp.lz"
OnixBackpic::           INCBIN "gfx/pokemon/monback/onixb.2bpp.lz"
DrowzeeFrontpic::       INCBIN "gfx/pokemon/monfront/drowzee.2bpp.lz"
DrowzeeBackpic::        INCBIN "gfx/pokemon/monback/drowzeeb.2bpp.lz"
HypnoFrontpic::         INCBIN "gfx/pokemon/monfront/hypno.2bpp.lz"
HypnoBackpic::          INCBIN "gfx/pokemon/monback/hypnob.2bpp.lz"
KrabbyFrontpic::        INCBIN "gfx/pokemon/monfront/krabby.2bpp.lz"
KrabbyBackpic::         INCBIN "gfx/pokemon/monback/krabbyb.2bpp.lz"
KinglerFrontpic::       INCBIN "gfx/pokemon/monfront/kingler.2bpp.lz"
KinglerBackpic::        INCBIN "gfx/pokemon/monback/kinglerb.2bpp.lz"
VoltorbFrontpic::       INCBIN "gfx/pokemon/monfront/voltorb.2bpp.lz"
VoltorbBackpic::        INCBIN "gfx/pokemon/monback/voltorbb.2bpp.lz"
ElectrodeFrontpic::     INCBIN "gfx/pokemon/monfront/electrode.2bpp.lz"
ElectrodeBackpic::      INCBIN "gfx/pokemon/monback/electrodeb.2bpp.lz"
ExeggcuteFrontpic::     INCBIN "gfx/pokemon/monfront/exeggcute.2bpp.lz"
ExeggcuteBackpic::      INCBIN "gfx/pokemon/monback/exeggcuteb.2bpp.lz"
ExeggutorFrontpic::     INCBIN "gfx/pokemon/monfront/exeggutor.2bpp.lz"
ExeggutorBackpic::      INCBIN "gfx/pokemon/monback/exeggutorb.2bpp.lz"
CuboneFrontpic::        INCBIN "gfx/pokemon/monfront/cubone.2bpp.lz"
CuboneBackpic::         INCBIN "gfx/pokemon/monback/cuboneb.2bpp.lz"
MarowakFrontpic::       INCBIN "gfx/pokemon/monfront/marowak.2bpp.lz"
MarowakBackpic::        INCBIN "gfx/pokemon/monback/marowakb.2bpp.lz"
HitmonleeFrontpic::     INCBIN "gfx/pokemon/monfront/hitmonlee.2bpp.lz"
HitmonleeBackpic::      INCBIN "gfx/pokemon/monback/hitmonleeb.2bpp.lz"


SECTION "Pics 6",ROMX

HitmonchanFrontpic::    INCBIN "gfx/pokemon/monfront/hitmonchan.2bpp.lz"
HitmonchanBackpic::     INCBIN "gfx/pokemon/monback/hitmonchanb.2bpp.lz"
LickitungFrontpic::     INCBIN "gfx/pokemon/monfront/lickitung.2bpp.lz"
LickitungBackpic::      INCBIN "gfx/pokemon/monback/lickitungb.2bpp.lz"
KoffingFrontpic::       INCBIN "gfx/pokemon/monfront/koffing.2bpp.lz"
KoffingBackpic::        INCBIN "gfx/pokemon/monback/koffingb.2bpp.lz"
WeezingFrontpic::       INCBIN "gfx/pokemon/monfront/weezing.2bpp.lz"
WeezingBackpic::        INCBIN "gfx/pokemon/monback/weezingb.2bpp.lz"
RhyhornFrontpic::       INCBIN "gfx/pokemon/monfront/rhyhorn.2bpp.lz"
RhyhornBackpic::        INCBIN "gfx/pokemon/monback/rhyhornb.2bpp.lz"
RhydonFrontpic::        INCBIN "gfx/pokemon/monfront/rhydon.2bpp.lz"
RhydonBackpic::         INCBIN "gfx/pokemon/monback/rhydonb.2bpp.lz"
ChanseyFrontpic::       INCBIN "gfx/pokemon/monfront/chansey.2bpp.lz"
ChanseyBackpic::        INCBIN "gfx/pokemon/monback/chanseyb.2bpp.lz"
TangelaFrontpic::       INCBIN "gfx/pokemon/monfront/tangela.2bpp.lz"
TangelaBackpic::        INCBIN "gfx/pokemon/monback/tangelab.2bpp.lz"
KangaskhanFrontpic::    INCBIN "gfx/pokemon/monfront/kangaskhan.2bpp.lz"
KangaskhanBackpic::     INCBIN "gfx/pokemon/monback/kangaskhanb.2bpp.lz"
HorseaFrontpic::        INCBIN "gfx/pokemon/monfront/horsea.2bpp.lz"
HorseaBackpic::         INCBIN "gfx/pokemon/monback/horseab.2bpp.lz"
SeadraFrontpic::        INCBIN "gfx/pokemon/monfront/seadra.2bpp.lz"
SeadraBackpic::         INCBIN "gfx/pokemon/monback/seadrab.2bpp.lz"
GoldeenFrontpic::       INCBIN "gfx/pokemon/monfront/goldeen.2bpp.lz"
GoldeenBackpic::        INCBIN "gfx/pokemon/monback/goldeenb.2bpp.lz"
SeakingFrontpic::       INCBIN "gfx/pokemon/monfront/seaking.2bpp.lz"
SeakingBackpic::        INCBIN "gfx/pokemon/monback/seakingb.2bpp.lz"
StaryuFrontpic::        INCBIN "gfx/pokemon/monfront/staryu.2bpp.lz"
StaryuBackpic::         INCBIN "gfx/pokemon/monback/staryub.2bpp.lz"
StarmieFrontpic::       INCBIN "gfx/pokemon/monfront/starmie.2bpp.lz"
StarmieBackpic::        INCBIN "gfx/pokemon/monback/starmieb.2bpp.lz"
MrMimeFrontpic::        INCBIN "gfx/pokemon/monfront/mr__mime.2bpp.lz"
MrMimeBackpic::         INCBIN "gfx/pokemon/monback/mr.mimeb.2bpp.lz"
ScytherFrontpic::       INCBIN "gfx/pokemon/monfront/scyther.2bpp.lz"
ScytherBackpic::        INCBIN "gfx/pokemon/monback/scytherb.2bpp.lz"
JynxFrontpic::          INCBIN "gfx/pokemon/monfront/jynx.2bpp.lz"
JynxBackpic::           INCBIN "gfx/pokemon/monback/jynxb.2bpp.lz"
ElectabuzzFrontpic::    INCBIN "gfx/pokemon/monfront/electabuzz.2bpp.lz"
ElectabuzzBackpic::     INCBIN "gfx/pokemon/monback/electabuzzb.2bpp.lz"


SECTION "Pics 7",ROMX

MagmarFrontpic::        INCBIN "gfx/pokemon/monfront/magmar.2bpp.lz"
MagmarBackpic::         INCBIN "gfx/pokemon/monback/magmarb.2bpp.lz"
PinsirFrontpic::        INCBIN "gfx/pokemon/monfront/pinsir.2bpp.lz"
PinsirBackpic::         INCBIN "gfx/pokemon/monback/pinsirb.2bpp.lz"
TaurosFrontpic::        INCBIN "gfx/pokemon/monfront/tauros.2bpp.lz"
TaurosBackpic::         INCBIN "gfx/pokemon/monback/taurosb.2bpp.lz"
MagikarpFrontpic::      INCBIN "gfx/pokemon/monfront/magikarp.2bpp.lz"
MagikarpBackpic::       INCBIN "gfx/pokemon/monback/magikarpb.2bpp.lz"
GyaradosFrontpic::      INCBIN "gfx/pokemon/monfront/gyarados.2bpp.lz"
GyaradosBackpic::       INCBIN "gfx/pokemon/monback/gyaradosb.2bpp.lz"
LaprasFrontpic::        INCBIN "gfx/pokemon/monfront/lapras.2bpp.lz"
LaprasBackpic::         INCBIN "gfx/pokemon/monback/laprasb.2bpp.lz"
DittoFrontpic::         INCBIN "gfx/pokemon/monfront/ditto.2bpp.lz"
DittoBackpic::          INCBIN "gfx/pokemon/monback/dittob.2bpp.lz"
EeveeFrontpic::         INCBIN "gfx/pokemon/monfront/eevee.2bpp.lz"
EeveeBackpic::          INCBIN "gfx/pokemon/monback/eeveeb.2bpp.lz"
VaporeonFrontpic::      INCBIN "gfx/pokemon/monfront/vaporeon.2bpp.lz"
VaporeonBackpic::       INCBIN "gfx/pokemon/monback/vaporeonb.2bpp.lz"
JolteonFrontpic::       INCBIN "gfx/pokemon/monfront/jolteon.2bpp.lz"
JolteonBackpic::        INCBIN "gfx/pokemon/monback/jolteonb.2bpp.lz"
FlareonFrontpic::       INCBIN "gfx/pokemon/monfront/flareon.2bpp.lz"
FlareonBackpic::        INCBIN "gfx/pokemon/monback/flareonb.2bpp.lz"
PorygonFrontpic::       INCBIN "gfx/pokemon/monfront/porygon.2bpp.lz"
PorygonBackpic::        INCBIN "gfx/pokemon/monback/porygonb.2bpp.lz"
OmanyteFrontpic::       INCBIN "gfx/pokemon/monfront/omanyte.2bpp.lz"
OmanyteBackpic::        INCBIN "gfx/pokemon/monback/omanyteb.2bpp.lz"
OmastarFrontpic::       INCBIN "gfx/pokemon/monfront/omastar.2bpp.lz"
OmastarBackpic::        INCBIN "gfx/pokemon/monback/omastarb.2bpp.lz"
KabutoFrontpic::        INCBIN "gfx/pokemon/monfront/kabuto.2bpp.lz"
KabutoBackpic::         INCBIN "gfx/pokemon/monback/kabutob.2bpp.lz"
KabutopsFrontpic::      INCBIN "gfx/pokemon/monfront/kabutops.2bpp.lz"
KabutopsBackpic::       INCBIN "gfx/pokemon/monback/kabutopsb.2bpp.lz"
AerodactylFrontpic::    INCBIN "gfx/pokemon/monfront/aerodactyl.2bpp.lz"
AerodactylBackpic::     INCBIN "gfx/pokemon/monback/aerodactylb.2bpp.lz"
SnorlaxFrontpic::       INCBIN "gfx/pokemon/monfront/snorlax.2bpp.lz"
SnorlaxBackpic::        INCBIN "gfx/pokemon/monback/snorlaxb.2bpp.lz"
ArticunoFrontpic::      INCBIN "gfx/pokemon/monfront/articuno.2bpp.lz"
ArticunoBackpic::       INCBIN "gfx/pokemon/monback/articunob.2bpp.lz"
ZapdosFrontpic::        INCBIN "gfx/pokemon/monfront/zapdos.2bpp.lz"
ZapdosBackpic::         INCBIN "gfx/pokemon/monback/zapdosb.2bpp.lz"


SECTION "Pics 8", ROMX

MoltresFrontpic::       INCBIN "gfx/pokemon/monfront/moltres.2bpp.lz"
MoltresBackpic::        INCBIN "gfx/pokemon/monback/moltresb.2bpp.lz"
DratiniFrontpic::       INCBIN "gfx/pokemon/monfront/dratini.2bpp.lz"
DratiniBackpic::        INCBIN "gfx/pokemon/monback/dratinib.2bpp.lz"
DragonairFrontpic::     INCBIN "gfx/pokemon/monfront/dragonair.2bpp.lz"
DragonairBackpic::      INCBIN "gfx/pokemon/monback/dragonairb.2bpp.lz"
DragoniteFrontpic::     INCBIN "gfx/pokemon/monfront/dragonite.2bpp.lz"
DragoniteBackpic::      INCBIN "gfx/pokemon/monback/dragoniteb.2bpp.lz"
MewtwoFrontpic::        INCBIN "gfx/pokemon/monfront/mewtwo.2bpp.lz"
MewtwoBackpic::         INCBIN "gfx/pokemon/monback/mewtwob.2bpp.lz"
MewFrontpic::           INCBIN "gfx/pokemon/monfront/mew.2bpp.lz"
MewBackpic::            INCBIN "gfx/pokemon/monback/mewb.2bpp.lz"


SECTION "Pics 9", ROMX

UnownAFrontpic::  INCBIN "gfx/pokemon/unown_a/front.2bpp.lz"
UnownABackpic::   INCBIN "gfx/pokemon/unown_a/back.2bpp.lz"
UnownBFrontpic::  INCBIN "gfx/pokemon/unown_b/front.2bpp.lz"
UnownBBackpic::   INCBIN "gfx/pokemon/unown_b/back.2bpp.lz"
UnownCFrontpic::  INCBIN "gfx/pokemon/unown_c/front.2bpp.lz"
UnownCBackpic::   INCBIN "gfx/pokemon/unown_c/back.2bpp.lz"
UnownDFrontpic::  INCBIN "gfx/pokemon/unown_d/front.2bpp.lz"
UnownDBackpic::   INCBIN "gfx/pokemon/unown_d/back.2bpp.lz"
UnownEFrontpic::  INCBIN "gfx/pokemon/unown_e/front.2bpp.lz"
UnownEBackpic::   INCBIN "gfx/pokemon/unown_e/back.2bpp.lz"
UnownFFrontpic::  INCBIN "gfx/pokemon/unown_f/front.2bpp.lz"
UnownFBackpic::   INCBIN "gfx/pokemon/unown_f/back.2bpp.lz"
UnownGFrontpic::  INCBIN "gfx/pokemon/unown_g/front.2bpp.lz"
UnownGBackpic::   INCBIN "gfx/pokemon/unown_g/back.2bpp.lz"
UnownHFrontpic::  INCBIN "gfx/pokemon/unown_h/front.2bpp.lz"
UnownHBackpic::   INCBIN "gfx/pokemon/unown_h/back.2bpp.lz"
UnownIFrontpic::  INCBIN "gfx/pokemon/unown_i/front.2bpp.lz"
UnownIBackpic::   INCBIN "gfx/pokemon/unown_i/back.2bpp.lz"
UnownJFrontpic::  INCBIN "gfx/pokemon/unown_j/front.2bpp.lz"
UnownJBackpic::   INCBIN "gfx/pokemon/unown_j/back.2bpp.lz"
UnownKFrontpic::  INCBIN "gfx/pokemon/unown_k/front.2bpp.lz"
UnownKBackpic::   INCBIN "gfx/pokemon/unown_k/back.2bpp.lz"
UnownLFrontpic::  INCBIN "gfx/pokemon/unown_l/front.2bpp.lz"
UnownLBackpic::   INCBIN "gfx/pokemon/unown_l/back.2bpp.lz"
UnownMFrontpic::  INCBIN "gfx/pokemon/unown_m/front.2bpp.lz"
UnownMBackpic::   INCBIN "gfx/pokemon/unown_m/back.2bpp.lz"
UnownNFrontpic::  INCBIN "gfx/pokemon/unown_n/front.2bpp.lz"
UnownNBackpic::   INCBIN "gfx/pokemon/unown_n/back.2bpp.lz"
UnownOFrontpic::  INCBIN "gfx/pokemon/unown_o/front.2bpp.lz"
UnownOBackpic::   INCBIN "gfx/pokemon/unown_o/back.2bpp.lz"
UnownPFrontpic::  INCBIN "gfx/pokemon/unown_p/front.2bpp.lz"
UnownPBackpic::   INCBIN "gfx/pokemon/unown_p/back.2bpp.lz"
UnownQFrontpic::  INCBIN "gfx/pokemon/unown_q/front.2bpp.lz"
UnownQBackpic::   INCBIN "gfx/pokemon/unown_q/back.2bpp.lz"
UnownRFrontpic::  INCBIN "gfx/pokemon/unown_r/front.2bpp.lz"
UnownRBackpic::   INCBIN "gfx/pokemon/unown_r/back.2bpp.lz"
UnownSFrontpic::  INCBIN "gfx/pokemon/unown_s/front.2bpp.lz"
UnownSBackpic::   INCBIN "gfx/pokemon/unown_s/back.2bpp.lz"
UnownTFrontpic::  INCBIN "gfx/pokemon/unown_t/front.2bpp.lz"
UnownTBackpic::   INCBIN "gfx/pokemon/unown_t/back.2bpp.lz"
UnownUFrontpic::  INCBIN "gfx/pokemon/unown_u/front.2bpp.lz"
UnownUBackpic::   INCBIN "gfx/pokemon/unown_u/back.2bpp.lz"
UnownVFrontpic::  INCBIN "gfx/pokemon/unown_v/front.2bpp.lz"
UnownVBackpic::   INCBIN "gfx/pokemon/unown_v/back.2bpp.lz"
UnownWFrontpic::  INCBIN "gfx/pokemon/unown_w/front.2bpp.lz"
UnownWBackpic::   INCBIN "gfx/pokemon/unown_w/back.2bpp.lz"
UnownXFrontpic::  INCBIN "gfx/pokemon/unown_x/front.2bpp.lz"
UnownXBackpic::   INCBIN "gfx/pokemon/unown_x/back.2bpp.lz"
UnownYFrontpic::  INCBIN "gfx/pokemon/unown_y/front.2bpp.lz"
UnownYBackpic::   INCBIN "gfx/pokemon/unown_y/back.2bpp.lz"
UnownZFrontpic::  INCBIN "gfx/pokemon/unown_z/front.2bpp.lz"
UnownZBackpic::   INCBIN "gfx/pokemon/unown_z/back.2bpp.lz"


; Trainer Pics

SECTION "Pics 10", ROMX

FalknerPic::      INCBIN "gfx/trainers/falkner.2bpp.lz"
WhitneyPic::      INCBIN "gfx/trainers/whitney.2bpp.lz"
BugsyPic::        INCBIN "gfx/trainers/bugsy.2bpp.lz"
MortyPic::        INCBIN "gfx/trainers/morty.2bpp.lz"
PrycePic::        INCBIN "gfx/trainers/pryce.2bpp.lz"
JasminePic::      INCBIN "gfx/trainers/jasmine.2bpp.lz"
ChuckPic::        INCBIN "gfx/trainers/chuck.2bpp.lz"
ClairPic::        INCBIN "gfx/trainers/clair.2bpp.lz"
Rival1Pic::       INCBIN "gfx/trainers/rival1.2bpp.lz"
PokemonProfPic::  INCBIN "gfx/trainers/oak.2bpp.lz"
WillPic::         INCBIN "gfx/trainers/will.2bpp.lz"
CalPic::          INCBIN "gfx/trainers/cal.2bpp.lz"
BrunoPic::        INCBIN "gfx/trainers/bruno.2bpp.lz"
KarenPic::        INCBIN "gfx/trainers/karen.2bpp.lz"
KogaPic::         INCBIN "gfx/trainers/koga.2bpp.lz"
ChampionPic::     INCBIN "gfx/trainers/champion.2bpp.lz"
BrockPic::        INCBIN "gfx/trainers/brock.2bpp.lz"
MistyPic::        INCBIN "gfx/trainers/misty.2bpp.lz"
LtSurgePic::      INCBIN "gfx/trainers/lt_surge.2bpp.lz"
ScientistPic::    INCBIN "gfx/trainers/scientist.2bpp.lz"
ErikaPic::        INCBIN "gfx/trainers/erika.2bpp.lz"
YoungsterPic::    INCBIN "gfx/trainers/youngster.2bpp.lz"
SchoolboyPic::    INCBIN "gfx/trainers/schoolboy.2bpp.lz"
BirdKeeperPic::   INCBIN "gfx/trainers/bird_keeper.2bpp.lz"
LassPic::         INCBIN "gfx/trainers/lass.2bpp.lz"
JaninePic::       INCBIN "gfx/trainers/janine.2bpp.lz"
CooltrainermPic:: INCBIN "gfx/trainers/cooltrainer_m.2bpp.lz"
CooltrainerfPic:: INCBIN "gfx/trainers/cooltrainer_f.2bpp.lz"
BeautyPic::       INCBIN "gfx/trainers/beauty.2bpp.lz"
PokemaniacPic::   INCBIN "gfx/trainers/pokemaniac.2bpp.lz"
GruntmPic::       INCBIN "gfx/trainers/grunt_m.2bpp.lz"
GentlemanPic::    INCBIN "gfx/trainers/gentleman.2bpp.lz"
SkierPic::        INCBIN "gfx/trainers/skier.2bpp.lz"
TeacherPic::      INCBIN "gfx/trainers/teacher.2bpp.lz"
SabrinaPic::      INCBIN "gfx/trainers/sabrina.2bpp.lz"
BugCatcherPic::   INCBIN "gfx/trainers/bug_catcher.2bpp.lz"
FisherPic::       INCBIN "gfx/trainers/fisher.2bpp.lz"
SwimmermPic::     INCBIN "gfx/trainers/swimmer_m.2bpp.lz"
SwimmerfPic::     INCBIN "gfx/trainers/swimmer_f.2bpp.lz"
SailorPic::       INCBIN "gfx/trainers/sailor.2bpp.lz"
SuperNerdPic::    INCBIN "gfx/trainers/super_nerd.2bpp.lz"
Rival2Pic::       INCBIN "gfx/trainers/rival2.2bpp.lz"
GuitaristPic::    INCBIN "gfx/trainers/guitarist.2bpp.lz"


SECTION "Pics 11", ROMX

HikerPic::        INCBIN "gfx/trainers/hiker.2bpp.lz"
BikerPic::        INCBIN "gfx/trainers/biker.2bpp.lz"
BlainePic::       INCBIN "gfx/trainers/blaine.2bpp.lz"
BurglarPic::      INCBIN "gfx/trainers/burglar.2bpp.lz"
FirebreatherPic:: INCBIN "gfx/trainers/firebreather.2bpp.lz"
JugglerPic::      INCBIN "gfx/trainers/juggler.2bpp.lz"
BlackbeltTPic::   INCBIN "gfx/trainers/blackbelt_t.2bpp.lz"
ExecutivemPic::   INCBIN "gfx/trainers/executive_m.2bpp.lz"
PsychicTPic::     INCBIN "gfx/trainers/psychic_t.2bpp.lz"
PicnickerPic::    INCBIN "gfx/trainers/picnicker.2bpp.lz"
CamperPic::       INCBIN "gfx/trainers/camper.2bpp.lz"
ExecutivefPic::   INCBIN "gfx/trainers/executive_f.2bpp.lz"
SagePic::         INCBIN "gfx/trainers/sage.2bpp.lz"
MediumPic::       INCBIN "gfx/trainers/medium.2bpp.lz"
BoarderPic::      INCBIN "gfx/trainers/boarder.2bpp.lz"
PokefanmPic::     INCBIN "gfx/trainers/pokefan_m.2bpp.lz"
KimonoGirlPic::   INCBIN "gfx/trainers/kimono_girl.2bpp.lz"
TwinsPic::        INCBIN "gfx/trainers/twins.2bpp.lz"
PokefanfPic::     INCBIN "gfx/trainers/pokefan_f.2bpp.lz"
RedPic::          INCBIN "gfx/trainers/red.2bpp.lz"
BluePic::         INCBIN "gfx/trainers/blue.2bpp.lz"
OfficerPic::      INCBIN "gfx/trainers/officer.2bpp.lz"
GruntfPic::       INCBIN "gfx/trainers/grunt_f.2bpp.lz"

SECTION "Pics 12", ROMX

SECTION "Pics 13", ROMX

SECTION "Pics 14", ROMX

SECTION "Pics 15", ROMX

SECTION "Pics 16", ROMX

SECTION "Pics 17", ROMX

SECTION "Pics 18", ROMX
